### ISSUE TITLE
Possible to dynamically change view id?

### ISSUE THREAD

**Issue by rorymcdaniel** [spatie/laravel-analytics#100]
I'm hoping to use this for a dashboard, where we would look at the analytics for multiple websites. Do you have any suggestions on how to make this happen? It seems to me the answer is likely in AnalyticsServiceProvider.php, but I'm not coming up with any good ideas on how to accomplish this. 

Any suggestions?

**Comment by rorymcdaniel** [comment]
Of course, I figured out the solution right after I asked, posted in case anyone else comes along this and is searching for the same answer. I created a helper class with a facade to access it. The actual helper class looks like this:

```
public function getView($viewId)
    {
        $config = config('laravel-analytics');
        $client = AnalyticsClientFactory::createForConfig($config);
        return new Analytics($client, $viewId);

    }
```

And I use it like this

```
$analytics = AnalyticsHelper::getView($viewId);
$analytics->fetchMostVisitedPages(Period::days(7));
```

If you're interested it in including it, I'd be glad to do the work and create a pull request.

**Comment by sebastiandedeyne** [comment]
Glad to see it got figured out 👍 

I think this is a slight edge case though, and it isn't too hard to implement outside of the package, so I don't think we'd include it.

**Comment by xron89** [comment]
I also require the ability to dynamically change the view id but couldn't get the above to work, could the op provide any more information on the solution.

**Comment by ashleybakernz** [comment]
@rorymcdaniel I'm trying to set this up but I'm new to Helper Classes. Any help would be awesome!

**Comment by DeClaessens** [comment]
Works like a charm!

@ashleybakernz in case it is still relevant.

I'll quickly explain the method I used
You first need to create a Helper class in app/Helpers
It should be called "AnalyticsHelper"

Fill the file with the following code
```
<?php
namespace Dashboard\Helpers;

use Spatie\Analytics\Analytics;
use Spatie\Analytics\AnalyticsClientFactory;

class AnalyticsHelper {

    public function getView($viewId)
    {
        $config = config('analytics');
        $client = AnalyticsClientFactory::createForConfig($config);
        return new Analytics($client, $viewId);
    }
}
```

Next up, add this to you `config/app.php` file under Aliases.
`        'AnalyticsHelper' => Dashboard\Helpers\AnalyticsHelper::class,
`

Finally, and this is my personal preference, inject it into your controller

```
private $helper;

    public function __construct(AnalyticsHelper $helper)
    {
        $this->helper = $helper;
    }
```

You can now call this.
`        $analytics = $this->helper->getView(69367325);
`


Hope it helps, and sorry if this wasn't the right place to post this. I figured the next guy who needs this might find it valuable.

**Comment by ashleybakernz** [comment]
Thank's I'll definitely give this ago!

**Comment by Mustafa-Omran** [comment]
**may be need config() helper to overwrite analytics file**

```
    public function getView($viewId)
    {
        config(['analytics.view_id' => $viewId]);
        $config = config('analytics');
        $client = AnalyticsClientFactory::createForConfig($config);
        return new Analytics($client, $viewId);
    }

```

**Comment by abbddkr** [comment]
@rorymcdaniel i can't get any result , it is return `{ }` 

Controller 
`      $analytics = $this->helper->getView('xxxxxx');
      $analytics->Analytics::fetchVisitorsAndPageViews(Period::months(6));
      $data = json_encode($analytics, JSON_UNESCAPED_SLASHES ); 
      return $data;      
`

**Comment by abbddkr** [comment]
@Mustafa-Omran good solution, thanks
