### ISSUE TITLE
Visitors by sorting the same date?

### ISSUE THREAD

**Issue by Bobeta** [spatie/laravel-analytics#101]
I am doing this query:
$analyticsData = Spatieanalytics::fetchVisitorsAndPageViews(Period::days(7))

Which results in page views for various pages. In a module, I would like to display only the page visitors for all the pages for the last 7 days. What I would like to achieve is sort them by date so that if they're the same date, the visitors amount get added to that date. I started trying out something like this without success and got a bit stuck:

->groupBy(function($item){
                return $item->date->date->format('d-M-y')
            )});

Some help would be great!

**Comment by freekmurze** [comment]
Hi, 

your question is a bit out of scope for this package.  

Like you already know the methods of this package return instances of `Illumniate\Support\Collection`.  Be sure to go over the [official documentation](https://laravel.com/docs/5.2/eloquent-collections) to learn what's possible.

If you really want to master working with collections, read [this book](https://adamwathan.me/refactoring-to-collections/).

**Comment by hugofabricio** [comment]
```
        // Get google analytics data for last 7 days
        $visitorsData = Analytics::performQuery(Period::days(7), 'ga:users,ga:pageviews', ['dimensions' => 'ga:date']);
        $visitorsData = collect($visitorsData['rows'] ?? [])->map(function (array $dateRow) {
          return [
            'date' => Carbon::createFromFormat('Ymd', $dateRow[0]),
            'visitors' => (int) $dateRow[1],
            'pageViews' => (int) $dateRow[2]
          ];
        });
```

**Comment by nivv** [comment]
@hugofabricio Your example works, but only on some of my installs. Whats is the `??` operator for?

Getting below:

```
FatalErrorException in DashboardController.php line 33:
syntax error, unexpected '?'
```

**Comment by hugofabricio** [comment]
How version your php?

**Comment by hugofabricio** [comment]
http://php.net/manual/en/language.operators.comparison.php ?? is new operator in php 7.

**Comment by nivv** [comment]
@hugofabricio Ah, that's why then. My Homstead is using php 5.6 thanks!
