### ISSUE TITLE
(get) missing required param: 'ids'

### ISSUE THREAD

**Issue by Zhaugasharov** [spatie/laravel-analytics#102]
I use analutics 1.4.1 version. I have added to laravel-analytics.conf (ga: and another thinks) my settings. But i have exception
Google_Exception in Resource.php line 169:
(get) missing required param: 'ids'
 laravel-analytics.conf:
   ` [
        /*
         * The siteId is used to retrieve and display Google Analytics statistics
         * in the admin-section.
         *
         * Should look like: ga:xxxxxxxx.
         */
        'siteId' => env('ga:xxxxxxxx'),

        /*
         * Set the client id
         *
         * Should look like:
         * xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
         */
        'clientId' => env('xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com'),

        /*
         * Set the service account name
         *
         * Should look like:
         * xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@developer.gserviceaccount.com
         */
        'serviceEmail' => env('xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@developer.gserviceaccount.com'),

        /*
         * You need to download a p12-certifciate from the Google API console
         * Be sure to store this file in a secure location.
         */
        'certificatePath' => storage_path('app/adsad.p12'),

        /*
         * The amount of minutes the Google API responses will be cached.
         * If you set this to zero, the responses won't be cached at all.
         */
        'cacheLifetime' => 60 * 24 * 2,

        /*
         * The amount of seconds the Google API responses will be cached for
         * queries that use the real time query method. If you set this to zero,
         * the responses of real time queries won't be cached at all.
         */
        'realTimeCacheLifetimeInSeconds' => 5,
    ];`
Controller where i use analytic:
`use Carbon\Carbon;
use Illuminate\Support\Collection;
use LaravelAnalytics;
public function test()
{	
LaravelAnalytics::getTopReferrers();
}`

**Comment by freekmurze** [comment]
You seem to have forgotten to fill in a valid `siteId`.

**Comment by Zhaugasharov** [comment]
i have fill siteId only numbers and with ga:XXXXXX numbers the results is same baecause when he sending request to google siteId is null

**Comment by freekmurze** [comment]
`'siteId' => env('ga:xxxxxxxx')` --> did you remove the `env` call?

`'siteId' => 'ga:xxxxxxxx'`

**Comment by Zhaugasharov** [comment]
Damn man you have large balls it's help me than you

**Comment by Zhaugasharov** [comment]
this exception writted in https://github.com/spatie/laravel-analytics/tree/1.4.1
