### ISSUE TITLE
Vendor publish, nothing to publish

### ISSUE THREAD

**Issue by xron89** [spatie/laravel-analytics#103]
After running 

`php artisan vendor:publish --provider="Spatie\Analytics\AnalyticsServiceProvider"`

I get Nothing to publish for tag [].

This results in no config file being generated for the google analytic api keys

**Comment by freekmurze** [comment]
Did you add the service provider to `config/app.php`?

**Comment by xron89** [comment]
Yes, I've added the following to lines to my config file (in the relevant directory)

`Spatie\LaravelAnalytics\LaravelAnalyticsServiceProvider::class,`

`'Analytics' => Spatie\LaravelAnalytics\LaravelAnalyticsFacade::class,`

Then when I run the vendor:publish command it just returns "Nothing to publish for tag []."

**Comment by freekmurze** [comment]
Are you running PHP 7?

If not, please refer to [the docs of the previous version](https://github.com/spatie/laravel-analytics/tree/1.4.1).

**Comment by xron89** [comment]
Aha yes using 5.6, thanks!
