### ISSUE TITLE
ErrorException in AnalyticsClientFactory.php line 24: Undefined index: cache_location

### ISSUE THREAD

**Issue by KrGyan** [spatie/laravel-analytics#105]
I am getting below error, earlier it was working fine. I just changes my CACHE_DRIVER in .env to array form file as I needed this for user role component and along with this is I did composer update which loaded new version of Laravel-Analytics.

Please help.

**Comment by freekmurze** [comment]
Could you a key called `cache_location` to the `laravel-analytics.php` config file?

It should point to a directory where the package can store its caches:

Example
```php
'cache_location' => storage_path('app/laravel-google-analytics/google-cache/'),
```

**Comment by KrGyan** [comment]
Wow.. @freekmurze . I love the speed at which you guys reply. :) 

10/10 for your support.

Thanks and it worked like charm !!

**Comment by freekmurze** [comment]
🎉  Have fun using the package!
