### ISSUE TITLE
Custom query without returning a collection

### ISSUE THREAD

**Issue by xron89** [spatie/laravel-analytics#108]
Is it possible to write a query without returning a collection of results across a time period. For example; 

```php
public function fetchNewUsers(Period $period): Collection
    {
        $response = $this->performQuery(
            $period,
            'ga:newUsers',
            ['dimensions' => 'ga:date']
        );
        return collect($response['rows'] ?? [])->map(function (array $dateRow) {
            return [
                'date' => Carbon::createFromFormat('Ymd', $dateRow[0]),
                'visitors' => (int) $dateRow[1],
            ];
        });
    }
```

This returns 30 results with different value for each, is there a way to add up all the results across the period so it just returns a single integer.

**Comment by freekmurze** [comment]
A collection has a `sum` function with which you can easily convert a whole collection to a single number.
