### ISSUE TITLE
PHP Default types are getting Spatie namespace Laravel Homestead

### ISSUE THREAD

**Issue by seymourduncandevops** [spatie/laravel-analytics#109]
I accidentally posted this in `analytics-statistics` but it's actually a `laravel-analytics` issue.

I'm trying to set this up on Laravel 5.2 on homestead (using HHVM hack) but have been running into a lot of issues. With a default setup (following readme install instructs to the letter), I get this error out of the box:

```
ErrorException in AnalyticsClient.php line 39:
Argument 1 passed to Spatie\Analytics\AnalyticsClient::setCacheLifeTimeInMinutes() must be an instance of Spatie\Analytics\int, int given
```

Even after removing all type hinting from the spatie/ files, other odd issues seem to arise in Carbon which makes me think this issue is deeper than some duckpunching patches. Any thoughts on how to resolve?

**Comment by freekmurze** [comment]
This package does not support hhvm. Try using it with PHP 7.
