### ISSUE TITLE
Can you offset the Period end date?

### ISSUE THREAD

**Issue by xron89** [spatie/laravel-analytics#111]
I would like to fetch a months results starting one month ago, I created my own class called "oldPeriod" where I simply just added subMonth to the end of the endDate e.g. 

`$endDate = Carbon::today()->subMonth();`

(Off course you have to offset the start date also)

But then of course none of the querys are setup to accept the class "oldPeriod" and it seems like a lot of code to reproduce as it would be the same query just changing the "Period" to "oldPeriod". 

Is there any easy way of offsetting the endDate without going through what I'm currently doing

**Comment by freekmurze** [comment]
If you extend `oldPeriod` of our `Period` class, it should work.

**Comment by xron89** [comment]
Can you provide an example, as I cant seem to edit the periods and get it working. So far i'm only able to fetch analytics from todays date running back x days. I'm looking to compare this months with lasts for example...
