### ISSUE TITLE
[help]

### ISSUE THREAD

**Issue by it9xpro** [spatie/laravel-analytics#114]
[help]
I want to show by date but as you see, it
 is shown all like this

![screenshot_1](https://cloud.githubusercontent.com/assets/6617916/18429626/b16ed712-78fe-11e6-9ccd-b777e0507f92.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/6617916/18429629/b2f5db3a-78fe-11e6-927f-7c1a0601663d.png)

**Comment by freekmurze** [comment]
That function returns and collection in which each item has [these properties](https://github.com/spatie/laravel-analytics/blob/master/src/Analytics.php#L50-L57).

Try doing 

```php
dd(Analytics: fetchVisitorsAndPageviews(Period::days(14)->toArray()));
```

to see them in your project.

**Comment by it9xpro** [comment]
I want order date , like v1 $analyticsData = LaravelAnalytics::getVisitorsAndPageViews(30, $groupBy = 'date');  help me :(

**Comment by freekmurze** [comment]
The method returns a collection object. It has functions for sorting data, summing up data, and many more things.

Please review [the official documentation on Collections](https://laravel.com/docs/5.3/collections) to learn more.

**Comment by it9xpro** [comment]
Thank you very much.  @freekmurze
