### ISSUE TITLE
Setting a real period

### ISSUE THREAD

**Issue by ItzFarhan** [spatie/laravel-analytics#116]
I see the google queries are setup using a period class, however it's not actually a period of time it's just how many days before today do you want to fetch data. 

Is it possible to actually create a period of time e.g from the first day of the month it would be something like... 

`$start = new Carbon('last day of this month')->take(31);`

Or possibly there is a way already to just get a months results because if I do take 30 or take 31 I get 30 days from carbon::now which depending on the day is half way through a month.

**Comment by freekmurze** [comment]
The [constructor](https://github.com/spatie/laravel-analytics/blob/master/src/Period.php#L31) accepts two `DateTime` instances (`Carbon` instances are accepted too). You can pass any date you like to them.

You could also extend the `Period` class adding any method you like.

**Comment by ItzFarhan** [comment]
-- Please reply above this line --


Hello,

We got your help request! One of our team members will respond to you
as soon as possible.

Thanks!
