### ISSUE TITLE
Update to google/apiclient v2

### ISSUE THREAD

**Issue by adaojunior** [spatie/laravel-analytics#117]
Do you have plans to update to google/apiclient version 2 ?
Would you accept contributions to update it ?

**Comment by freekmurze** [comment]
On https://developers.google.com/api-client-library/php/ I read: "This client library is in beta. We will make an effort to support the library and maintain backwards compatibility in the future, but we reserve the right to make incompatible changes when necessary." That scares me a little bit.

I would accept a PR to update the client to V2 when the client is out of beta.

**Comment by adaojunior** [comment]
@freekmurze That message has been there since ever, btw you can see here that it is a major release: [google-api-php-client](https://github.com/google/google-api-php-client/releases)

**Comment by adaojunior** [comment]
@freekmurze Hi, I don't mean to bother, I just want to make sure you saw my last message. I think it may be a misunderstanding, maybe the concept of the google api for PHP is beta, but the V2 is not, it has ben through many RC before final release, I'm using your library on my company projects and we're holding on a new feature because we need to upgrade to google apis v2. I'm ok if you decide not to upgrade, but I may have to fork and use an alternative version until you decide to upgrade to v2.

**Comment by freekmurze** [comment]
Ok, I'd accept a PR that upgrade the api client to V2 preferably in a non breaking way.

**Comment by adaojunior** [comment]
ok, thank you

**Comment by it-can** [comment]
this would be nice :-)

**Comment by adaojunior** [comment]
I have been using it for a while: `"spatie/laravel-analytics": "v3.0.x-dev"`.

**Comment by sebastiandedeyne** [comment]
Gonna close this issue for now since it's part of #125!
