### ISSUE TITLE
Permission error after reinstall

### ISSUE THREAD

**Issue by Bobeta** [spatie/laravel-analytics#119]
I am getting the following error after reinstalling the plugin:

`local.ERROR: ErrorException: chmod(): Operation not permitted in /var/www/test-project/vendor/google/apiclient/src/Google/Cache/File.php:190`

This is the code from that line:
```
    if ($type == LOCK_EX) {
      chmod($storageFile, 0600);
    }
```

I suspect that it has something to do with permission settings on my server since it works fine on my local machine. Right now I have drwxr-xr-x (775) for storage and vendor. Any ideas?

**Comment by freekmurze** [comment]
Indeed, this probably has something to do with the permissions on your server. Dump the `$storageFile` to find out to which file it's trying to write.

**Comment by nam-co** [comment]
Hi, Im having the exact same problem, did you manage to fix this Bobeta? thanks

**Comment by Bobeta** [comment]
Hi nam-co, it was a permission error as I anticipated. In my case, it was that the sub-folders in storage had root as owner. I solved it simply by doing:

`sudo chown yourgroup:username storage -R`

Also check so that it has correct chmod.
