### ISSUE TITLE
Unable to fetch New & Returning Customers count. 

### ISSUE THREAD

**Issue by rahularctic** [spatie/laravel-analytics#122]
could you guide me in using "performQuery(Period $period, string $metrics, array $others = [])"
I need to fetch the following.
New Vs Returing Users Count
User Activity
bounceRate
avgSessionDuration

**Comment by freekmurze** [comment]
Hi, as I've not needed these statistics myself, I can't offer you any help here.

Please review Google's documentation on the subject.

https://developers.google.com/analytics/devguides/reporting/core/v3/common-queries
