### ISSUE TITLE
Using PerformQuery

### ISSUE THREAD

**Issue by rahularctic** [spatie/laravel-analytics#123]
As the metric parameter takes input and shows as expected,
I need to specify Dimension as a parameter to fetch some output.
Is there anyway to do so ?

All Traffic Sources - Usage

This query returns the site usage data broken down by source and medium, sorted by sessions in descending order.

```
dimensions=ga:source,ga:medium
metrics=ga:sessions,ga:pageviews,ga:sessionDuration,ga:exits
sort=-ga:sessions
```

Source : https://developers.google.com/analytics/devguides/reporting/core/v3/common-queries

**Comment by gui34** [comment]
Hi,
i specify dimensions with the last parameter (is an array), like this :
Analytics::performQuery($period,'ga:sessions',['dimensions' => 'ga:source'])

It works for me
