### ISSUE TITLE
Package doesn't work properly with PHP < 7 (5.6, in my case)

### ISSUE THREAD

**Issue by romulo-rocha** [spatie/laravel-analytics#124]
I've been taught that this package is recommended for **PHP 7**. However, is there a way I can get this working on **PHP 5.6**, for instance? I've done that workaround on the **laravel-analytics config file** so it would properly call the classes, but now I've realized the downloaded package files by composer are just not the same as the ones shown in this repository.

In the _vendor/spatie/laravel-analytics/src_ I have the following files:
- GoogleApiHelper.php;
- LaravelAnalytics.php;
- LaravelAnalyticsFacade.php;
- LaravelAnalyticsServiceProvider.php.

There is no _Period.php_ file and others. This is preventing me from using the package as an error occurs everytime I try to perform a request. For example, if I try to:

`$analyticsData = Analytics::fetchVisitorsAndPageViews(Period::days(7));`

_fetchVisitorsAndPageViews_ is an undefined method and _Period_ doesn't exist.

My only query is: is there a way to support and use this package in predecessor versions of PHP 7? If no, I fear I might not be allowed to upgrade the PHP I'm using for the current project and shall leave this package, which I became really fond of. :(

Thanks in advance.

**Comment by freekmurze** [comment]
If you want to use this package, but can't upgrade to PHP 7 I suggest your create your own fork of the code in which you remove all PHP 7 features (scalar type hints, return types, null coalesence, anonymous classes, etc) and replace it by PHP 5.6 code.

**Comment by romulo-rocha** [comment]
I suggest you to document the version required for this package in the README file.
Thanks!

**Comment by Gummibeer** [comment]
@romulo-rocha: it is in the composer.json https://github.com/spatie/laravel-analytics/blob/master/composer.json you shouldn't be able to install it with php 5.6
