### ISSUE TITLE
Finishing v3

### ISSUE THREAD

**Issue by freekmurze** [spatie/laravel-analytics#125]
Pinging @adaojunior 

In this issue when can discuss what needs to be done before tagging v3. 

Let me know when you are done testing the `v3` branch.

**Comment by adaojunior** [comment]
@freekmurze I upgraded to `v3.0.x-dev` from `^1.3` and it worked fine so far.
I'll keep an eye for the next few days, I use it mostly on a console command that runs every day, and after I upgraded to google client v2 I had some trouble with the authentication in the very second day, it was fixed once I deleted all the cached files. I'll see if it happens again.

**Comment by freekmurze** [comment]
Is there something that needs to be changed regarding [obtaining credentials](https://github.com/spatie/laravel-analytics#how-to-obtain-the-credentials-to-communicate-with-google-analytics) in our readme? Or does all that still applies for v2 of google client as well?

**Comment by adaojunior** [comment]
@freekmurze I don't think so, that seems right to me.

**Comment by adaojunior** [comment]
Hi @freekmurze 

I'll update the v3 branch to support laravel 5.4

```
    "illuminate/contracts": "~5.3.0|~5.4.0",
    "illuminate/support": "~5.3.0|~5.4.0",
```

**Comment by clarkewing** [comment]
Any plans to release v3 in the near future?

**Comment by freekmurze** [comment]
Currently this package is a bit low on the priority list. I'll try to make some time soon.

**Comment by freekmurze** [comment]
`v3` has been released 🎉
