### ISSUE TITLE
Laravel 4.2 support

### ISSUE THREAD

**Issue by johnef** [spatie/laravel-analytics#126]
Laravel 4.2 support dose it have support to laravel 4.2 PHP v5.4.45

**Comment by sebastiandedeyne** [comment]
Check out spatie/analytics-statistics for Laravel 4.2 support!

**Comment by johnef** [comment]
composer require spatie/analytics-statistics
got Error.
Installation failed, reverting ./composer.json to its original content

**Comment by sebastiandedeyne** [comment]
Is there any additional info on the error?

**Comment by johnef** [comment]
here you are
 

> Problem 1
>     - Conclusion: don't install spatie/analytics-statistics 1.0.1
>     - Conclusion: remove nesbot/carbon 1.17.0
>     - Installation request for spatie/analytics-statistics ^1.0 -> satisfiable by spatie/analytics-statistics[1.0.0, 1.0.1].
>     - Conclusion: don't install nesbot/carbon 1.17.0
>     - spatie/analytics-statistics 1.0.0 requires nesbot/carbon ^1.19 -> satisfiable by nesbot/carbon[1.19.0, 1.20.0, 1.21.0].
>     - Can only install one of: nesbot/carbon[1.19.0, 1.17.0].
>     - Can only install one of: nesbot/carbon[1.20.0, 1.17.0].
>     - Can only install one of: nesbot/carbon[1.21.0, 1.17.0].

**Comment by sebastiandedeyne** [comment]
Could you share the contents of your `composer.json` file?

**Comment by johnef** [comment]
{
  "name": "laravel/laravel",
  "description": "The Laravel Framework.",
  "keywords": [
    "framework",
    "laravel"
  ],
  "license": "MIT",
  "require": {
    "laravel/framework": "4.2.*",
    "barryvdh/laravel-ide-helper": "~1.11",
    "arcanedev/no-captcha": "~1.2",
    "irazasyed/laravel-gamp": "~0.5",
    "jmpatricio/easy-google-analytics": "^1.0"
  },
  "autoload": {
    "classmap": [
      "app/commands",
      "app/controllers",
      "app/models",
      "app/database/migrations",
      "app/database/seeds",
      "app/tests/TestCase.php"
    ]
  },
  "scripts": {
    "post-install-cmd": [
      "php artisan clear-compiled",
      "php artisan optimize"
    ],
    "post-update-cmd": [
      "php artisan clear-compiled",
      "php artisan optimize"
    ],
    "post-create-project-cmd": [
      "php artisan key:generate"
    ]
  },
  "config": {
    "preferred-install": "dist"
  },
  "minimum-stability": "stable",
  "require-dev": {
    "way/generators": "^3.0"
  }
}

**Comment by sebastiandedeyne** [comment]
Answered at spatie/analytics-statistics#4
