### ISSUE TITLE
File.php line 190: chmod(): Operation not permitted

### ISSUE THREAD

**Issue by rulgf** [spatie/laravel-analytics#128]
Hi, Im using laravel analytics 1.4.1
Locally it works perfect but once in the server i got the error:

**ErrorException in File.php line 190:
chmod(): Operation not permitted**

I already tried changing permissions and owner of the project (including the storage folder) but nothing seems to work.
What can I be doing wrong ?

**Comment by ternavsky** [comment]
I have same issue, have you solved it?

**Comment by rulgf** [comment]
Hi @ternavsky,
I commented the line and it works fine. Just make sure the file chmod() is trying to change has the correct permissions.

Sincerely I don't know if it was the right way to solve this problem. I try different solutions from other users, but none of them worked.

**Comment by ternavsky** [comment]
For me problem was that laravel-analytics tried to access file cache (storage directory). And storage directory has wrong permissions. I set apache as owner to storage directory and it works! Command: sudo chown www-data:www-data storage (You may have something different from www-data as apache user, for ex. "httpd", search how to determine apache user in linux).

**Comment by rulgf** [comment]
Yep, This do the trick! Thanks @ternavsky

**Comment by jerremeirago** [comment]
exec('chmod ' . '-path- 777')

**Comment by iamdvs** [comment]
thanks
