### ISSUE TITLE
Cache not clearing / stats not updating

### ISSUE THREAD

**Issue by mradamwood** [spatie/laravel-analytics#129]
I've set my cache to 30 and 60  minutes but it doesn't appear to update unless I set to 0 and then refresh. Any advice on what / where to check?

**Comment by freekmurze** [comment]
We are just using Laravel's cache: https://github.com/spatie/laravel-analytics/blob/e5ae005d1d2dc440bb71133fe22ffd5ec824f8e0/src/AnalyticsClient.php#L15

Unsure why it isn't working at your end. Which driver are you using?

**Comment by mradamwood** [comment]
File on development, redis on staging / production. This morning it's all ok. I'm going to blame it on gremlins (or my brain wasn't in gear last night)! Thanks for reply. Closing.
