### ISSUE TITLE
Google OAuth2 Token Issue in OAuth2.php

### ISSUE THREAD

**Issue by hynospt** [spatie/laravel-analytics#130]
Hello , 
i still cannot get this right, i do not know , i think i have followed the instructions in readme.md so carefully 
i have been tried set the env and double checked it that my attributes is correct.

here is my .env

```
ANALYTICS_SITE_ID=ga:131661720
ANALYTICS_CLIENT_ID=930983209843-ua81ln6muba1lq66ra83vpq91ldn4ul8.apps.googleusercontent.com
ANALYTICS_SERVICE_EMAIL=sabbiaenergy@gmail.com
```

and i have set my right private key in config like this.
`'certificatePath' => storage_path('laravel-analytics/sabia-web-analytics-211f98cd6ade.p12'),`

The problem is when i want to get function getVisitorsAndPageViews(7)
its look like the api wont get work, here is the message :

> Error refreshing the OAuth2 token, message: '{
> "error" : "invalid_client",
> "error_description" : "The OAuth client was invalid."
> }'

I think the clientId has been set correctly right ? maybe someone could help me..
Thanks !!!

**Comment by sebastiandedeyne** [comment]
Do you still have this issue?
