### ISSUE TITLE
Multiple Site ID's

### ISSUE THREAD

**Issue by SteveChurch** [spatie/laravel-analytics#131]
Hi Guys,

I hope your all well. I have a requirement to use the Google API across multiple Site ID's however looking through your library this is passed via config in ENV. Could you please advise how I could use this for multiple sites. 

Kind Regards

**Comment by freekmurze** [comment]
Take a look at [this comment](https://github.com/spatie/laravel-analytics/issues/100#issuecomment-237330264) to learn how to use another `view id`.

**Comment by xron89** [comment]
Note to the original poster, the above isn't a working method the in-complete snippet shouldn't be used as a guide. I would recommend and looking to assign the site id config array item to an env variable and updating it that way. 

Unfortunately this plugin doesn't natively support multiple site id's.
