### ISSUE TITLE
install last version laravel-analytics

### ISSUE THREAD

**Issue by thaonguyen90** [spatie/laravel-analytics#133]
PHP 5.6 laravel 5.2. * When installing only version 1.4, the latest version of PHP 7 requirements. :((

"require": {
    "php" : "^7.0",
    "illuminate/contracts": "~5.1.0|~5.2.0|~5.3.0",
    "illuminate/support": "~5.1.0|~5.2.0|~5.3.0",
    "google/apiclient" : "^1.1",
    "nesbot/carbon": "^1.21"

  },

**Comment by freekmurze** [comment]
I don't know what your question is, but yea, the latest version requires PHP 7.
