### ISSUE TITLE
Error in Period.php

### ISSUE THREAD

**Issue by ootim** [spatie/laravel-analytics#134]
Hi,
I have followed the instructions for installing but I get this error:

FatalErrorException in Period.php line 17:
syntax error, unexpected ':', expecting ';' or '{'

I use php 7 and have the 2.3 version installed. Is there any other thing I should do to make it work?

Thanks

**Comment by freekmurze** [comment]
Are you sure you're using PHP when executing the code of the package? Put a `phpinfo()` right before that line just to make sure.

**Comment by ootim** [comment]
Hi,
Sorry to have bothered you! 

Using `phpinfo()` revealed that my server was still using php5 whereas I was checking via terminal with `php -v` which was showing php7. It happens that apache was still configured to use php5, changing it to php7 solved the problem.

Thanks.
