### ISSUE TITLE
Provide more information about configuration and use on readme.md

### ISSUE THREAD

**Issue by bantawa04** [spatie/laravel-analytics#135]
1. To add both 
 use Analytics;
use Spatie\Analytics\Period;
 in controllers.
2. To remove env() from laravel-analytics.php
 'view_id' field should look like this:
'view_id' => 'your_view_id',

3. And more on how to show show fetched data in views with demo and codes

**Comment by freekmurze** [comment]
I'd accept PR's that improve the readme.
