### ISSUE TITLE
Months

### ISSUE THREAD

**Issue by nam-co** [spatie/laravel-analytics#136]
Hi Freek, I was wondering if theres a way to get unified results of months, instead of days? hope you consider if there no way

Period::months(2), this will return september = xx, october = xx

thanks for your work
Michael

**Comment by freekmurze** [comment]
I believe you're looking for [the `dataMonth` dimension](https://developers.google.com/analytics/devguides/reporting/core/dimsmets#view=detail&group=time&jump=ga_yearmonth)

Out of the box this package doesn't provide calls with that dimension, but it's very easy to use the  `performQuery` function to make your own call to the Analytics service.
