### ISSUE TITLE
Nothing to publish for tag []. with vendor:publish

### ISSUE THREAD

**Issue by shinokada** [spatie/laravel-analytics#145]
When I run `php artisan vendor:publish --provider="Spatie\Analytics\AnalyticsServiceProvider"`, I get `Nothing to publish for tag [].`

Laravel framework version 5.3.28
PHP version 7.1.0

Any bug?

**Comment by freekmurze** [comment]
Did you install the service provider prior to running that command?

**Comment by shinokada** [comment]
Yes, I did. I copied it from source at the end. 

```
composer require spatie/laravel-analytics

// config/app.php
'providers' => [
    ...
    Spatie\Analytics\AnalyticsServiceProvider::class,
    ...
];

// config/app.php
'aliases' => [
    ...
    'Analytics' => Spatie\Analytics\AnalyticsFacade::class,
    ...
];
```

**Comment by freekmurze** [comment]
Does the `Spatie\Analytics\AnalyticsServiceProvider` exist? 

Are you sure you are running the right php version from the cli? You can test it by running `php -v`

**Comment by Aldairnatan** [comment]
I have the same problem!!

Configurations
Laravel Framework version 5.3.28
PHP version 7.0.11

**Comment by freekmurze** [comment]
Please check in your `composer.json` that you're pulling in `v2` of the package and not `v1`.

**Comment by Aldairnatan** [comment]
see composer.json
`{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "cviebrock/eloquent-sluggable": "4.1",
        "guzzlehttp/guzzle": "^6.2",
        "laravel/framework": "5.3.*",
        "spatie/laravel-analytics": "^2.3",
        "sun/sunmailer": "^1.4",
        "tsawler/laravel-filemanager": "^0.6.2",
        "yajra/laravel-disqus": "^0.1.2"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    }
}
`

**Comment by shinokada** [comment]
I found that I needed to run `php artisan config:clear` and run `php artisan vendor:publish --provider="Spatie\Analytics\AnalyticsServiceProvider"` again to work.

**Comment by logicbate** [comment]
php artisan config:clear 
go to app.php file copy and paste Spatie\Analytics\AnalyticsServiceProvider::class,
and php artisan vendor:publish --provider="Spatie\Analytics\AnalyticsServiceProvider"
end
