### ISSUE TITLE
How to retrieve data from performQuery

### ISSUE THREAD

**Issue by shinokada** [spatie/laravel-analytics#146]
I get Google_Service_Analytics_GaData from function `performQuery`.

    $country = Analytics::performQuery(Period::days(14),'ga:sessions',  ['dimensions'=>'ga:country',
    'sort'=>'-ga:sessions']);
    dd($country);

```
Google_Service_Analytics_GaData {#746 ▼
  #collection_key: "rows"
  #internal_gapi_mappings: []
  #columnHeadersType: "Google_Service_Analytics_GaDataColumnHeaders"
...
...
```

But when I use `pluck()`, I get an error.

    $country = Analytics::performQuery(Period::days(14),'ga:sessions',  ['dimensions'=>'ga:country',
    'sort'=>'-ga:sessions']);
    $this->data['country'] = $country->pluck('country'); 
    $this->data['country_session'] = $country->pluck('sessions'); 

> Error
> 
> Call to undefined method Google_Service_Analytics_GaData::pluck()

 What should I use instead of `pluck`?

**Comment by freekmurze** [comment]
Try this:

```php
collect($country)->pluck('country')
```

**Comment by shinokada** [comment]
This one worked. Thanks.

        $country = Analytics::performQuery(Period::days(14),'ga:sessions',  ['dimensions'=>'ga:country','sort'=>'-ga:sessions']);
        //$this->data['country'] = $country->getRows('country'); 
        $result= collect($country['rows'] ?? [])->map(function (array $dateRow) {
            return [
                'country' =>  $dateRow[0],
                'sessions' => (int) $dateRow[1],
            ];
        });
        $this->data['country'] = $result->pluck('country');
        $this->data['country_sessions'] = $result->pluck('sessions');
