### ISSUE TITLE
User does not have any Google Analytics account

### ISSUE THREAD

**Issue by HashmatWaziri** [spatie/laravel-analytics#149]
Error calling GET https://www.googleapis.com/analytics/v3/data/ga?ids=ga%3A12222260&start-date=2016-12-28&end-date=2017-01-04&metrics=ga%3Asessions: (403) User does not have any Google Analytics account.

What is the fix for this ?

Thanks

**Comment by freekmurze** [comment]
Probably you missed [this step](https://github.com/spatie/form-backend-validation-example-app) from the readme
