### ISSUE TITLE
Add PHP7 requirement Information to documentation

### ISSUE THREAD

**Issue by datune** [spatie/laravel-analytics#150]
Hello!

First, thanks for this package, much appreciated! Though I am sure you are well aware of this, and yes composer will automatically pull in other versions if PHP7 is not installed, it might be a good idea to add a small note to your documentation that from version X upwards PHP7 is a requirement (mostly because you chose to implement the null coalesce operator, at least from what I could spot from quickly glancing over your code). 

Cheers, 
Jürgen

**Comment by freekmurze** [comment]
Thank for your suggestion. However I'm going to leave it as it is. Developers who are not able to use the latest PHP version should have the reflex to check which version is being pulled in.
