### ISSUE TITLE
Support for Laravel 5.4.x

### ISSUE THREAD

**Issue by kcwoodfield** [spatie/laravel-analytics#151]
I'm trying to install this package and I keep getting an error.  Composer is screaming about Illuminate and Laravel versions.  Is there an easy way around this?

`Can only install one of: laravel/framework[5.4.x-dev, 5.3.x-dev]`

http://take.ms/w2RI3

**Comment by freekmurze** [comment]
We'll add support as soon as Laravel 5.4 is officially released.

**Comment by freekmurze** [comment]
Version `2.4.0` has support for Laravel 5.4.
