### ISSUE TITLE
Return devices & users

### ISSUE THREAD

**Issue by xron89** [spatie/laravel-analytics#152]
I'm having an issue returning the devices & users this is my query so far - 

 ```
public function fetchDeviceVisitors(Period $period): Collection
    {
        $response = $this->performQuery(
            $period,
            'ga:users',
            ['dimensions' => 'ga:deviceCategory']
        );

        dd($response);

        return collect($response['rows'] ?? [])
            ->map(function (array $pageRow) {

            });
    }
```

The response row thats return from the die dump shows a multi dimensional array with the following; 

```
 +rows: array:3 [▼
    0 => array:2 [▼
      0 => "desktop"
      1 => "69"
    ]

    1 => array:2 [▼
      0 => "mobile"
      1 => "28"
    ]

    2 => array:2 [▼
      0 => "tablet"
      1 => "2"
    ]
  ]

```
I was wondering how I could fetch this data in my query when the array is in this format

**Comment by sebastiandedeyne** [comment]
What format should your data be in? Could you post an example?

**Comment by sebastiandedeyne** [comment]
Closing this for now since it's been inactive for a while. Feel free to reopen if necessary!
