### ISSUE TITLE
Unable to install package "spatie/laravel-analytics"

### ISSUE THREAD

**Issue by princelionelnzi** [spatie/laravel-analytics#153]
I installed `spatie/laravel-analytics` using composer as follow "composer require spatie/laravel-analytics"

After running the above command, the version which got installed was the version "1.4" instead of the latest one which is "2.4".

I then went to my composer file to change manually the version to "2.3.1" and run "composer update".

And I got this error:

Problem 1
    - Installation request for spatie/laravel-analytics 2.3.1 -> satisfiable by spatie/laravel-analytics[2.3.0].
    - spatie/laravel-analytics 2.3.1 requires php ^7.0 -> your PHP version (5.6.24) does not satisfy that requirement.

I am running PHP 5.6, and from the documentation I can install the parkage.

Is there any way to help me out?

**Comment by freekmurze** [comment]
Version 2 of this package requires PHP 7. 

If you're stuck on PHP 5, use version 1 of the package.
