### ISSUE TITLE
Segmentation Fault when using caching

### ISSUE THREAD

**Issue by pbrisson** [spatie/laravel-analytics#155]
I'm getting a Segmentation Fault when using caching. Setting cache_lifetime_in_minutes options to 0 fix the issue.

We're grabbing a lot of data from our Analytics profile thought. Could that explain the issue?

My concern is I'm wondering why it would cause some segmentation fault issue... Circular reference maybe?

I'm running L5.1 on PHP 7.0 FPM.

Thanks!

**Comment by sebastiandedeyne** [comment]
Are you still having this issues? Sounds more like an issue with the specific version than with this package unfortunately...
