### ISSUE TITLE
Argument 1 passed to Spatie\Analytics\Period::days() must be an instance of int, int given

### ISSUE THREAD

**Issue by quinxy** [spatie/laravel-analytics#157]
Maybe I'm being stupid here, but I'm getting what seems like a very weird error.

ErrorException in Period.php line 29:
Argument 1 passed to Spatie\Analytics\Period::days() must be an instance of int, int given

Huh?  It wants int and I gave it an int and it's unhappy with me?

Here's the relevant pieces of code, i was just trying to get the demo working...

```
use LaravelAnalytics; // I had to add this otherwise it couldn't find Analytics
use Spatie\Analytics\Period;

$analytics = \Analytics::fetchVisitorsAndPageViews(Period::days(7)); // I had to use \Analytics otherwise it couldn't find Analytics

Providers:
        Spatie\Analytics\AnalyticsServiceProvider::class,

Aliases:
        'Analytics' => Spatie\Analytics\AnalyticsFacade::class,
```
Any input greatly appreciated, more so if I'm just being especially stupid.

**Comment by freekmurze** [comment]
The error message makes me think that you do not have PHP 7 installed. This package requires PHP 7.
