### ISSUE TITLE
Laravel LTS

### ISSUE THREAD

**Issue by devdurbs** [spatie/laravel-analytics#158]
With the new releases of laravel-analytics potentially breaking older release configs (e.g PHP7, Json vs p.12 etc) is there any possibility you might consider maintaining a release specifically for Laravel 5.1. I guess many users might be locked into 5.1 as it is Laravel's LTS release?

Thanks

**Comment by freekmurze** [comment]
I only maintain what I use myself. I'm not using legacy Laravel releases anymore. 

You're free to fork this package and maintain your own L5.1 compatible copy.

(Imho sticking on LTS releases for your applications is [a bad idea](https://medium.com/@jasonmccreary/laravel-lts-is-a-trap-97b1d1103961#.l0sl16utj))
