### ISSUE TITLE
Dynamically Setting SiteId Returns Error

### ISSUE THREAD

**Issue by winni4eva** [spatie/laravel-analytics#161]
Am trying to set the site id for my analytics requests dynamically using..
`
Analytics::setSiteId( $siteId )->performQuery($startDate, $endDate, 'ga:pageviews', $dimensions);
`
But I get error

`
Spatie\Analytics\Exceptions\InvalidConfiguration: There was no view id specified. You must provide a valid view id to execute querys on Google Analytics.
`

tried setting the view id using the laravel config helper but still getting the same error

`
config(['laravel-analytics.view_id' => $siteId]);
`

**Comment by sebastiandedeyne** [comment]
That's because the view id is required when the service provider gets registered.

Can you ensure the config value gets set before this package's service provider gets registered?

**Comment by winni4eva** [comment]
The view id's are stored in a database for different users. I need to be able to set it for every request I make depending on the user. Used to work with an earlier version of the package, I just upgraded and it started failing.

**Comment by sebastiandedeyne** [comment]
I think the easiest solution here would be to either:

- Extend it and set `$defer` to `true`, so it will only be initialised when you call it (after you've set the config value) [note: not sure if this would work!]
- Make a copy of the package's service provider, and create one in your app that retrieves the view ID for you instead of using the config value

**Comment by winni4eva** [comment]
Ok. thanks Sebastian will try them out and let you know if it worked

**Comment by winni4eva** [comment]
The first option seems to work, no longer getting 
`
Spatie\Analytics\Exceptions\InvalidConfiguration: There was no view id specified. You must provide a valid view id to execute querys on Google Analytics.
`

I seem to have a problem with my service_account_credentials_json 
'
Google_Exception: Invalid service account JSON file.
'
Will try and get it working. Thanks for your help.
