### ISSUE TITLE
How to test it on localserver?

### ISSUE THREAD

**Issue by RoyGaurav** [spatie/laravel-analytics#162]
I have installed and implemented it as per document. But I want to test it on local host but I am getting Collections of empty array.

Testing server : 127.0.0.1
port : 8000
![capture](https://cloud.githubusercontent.com/assets/6642434/23101596/35200e5a-f6bd-11e6-84e7-63c6112a5611.JPG)

**Comment by sebastiandedeyne** [comment]
Are you still experiencing this issue?

**Comment by andrehardika** [comment]
I've experienced this same issue. How to solve it? The configuration seems fine and right to me.

**Comment by AhmedSayedSk** [comment]
I've same issue, but i can't solve it! and ideas?

**Comment by mwei0210** [comment]
Same hereeeee, anyone has any idea?

**Comment by robertnicjoo** [comment]
nobody seem to have solution on this issue right? it's from 2017 and yet i couldn't find answer for it
