### ISSUE TITLE
syntax error, unexpected ':', expecting ';' or '{'

### ISSUE THREAD

**Issue by bantawa04** [spatie/laravel-analytics#163]
I have implemented laravel-analytics package in my application. At development (localhost:8000) it ran smoothly showing all data. It is returning me error `syntax error, unexpected ':', expecting ';' or '{'` in `vendor/spatie/laravel-analytics/src/Period.php` I have rendered data's from package in mu dashboard and due to this error i'm not able to login.

**Comment by Biggo6** [comment]
Hello ! i get the same error what is solution?

**Comment by freekmurze** [comment]
The latest version of this package requires PHP 7. You're probably on an older version.

**Comment by babalubas090** [comment]
I'm at PHP 7.0.22 and I gotthe same error...

But I think that I found the solution with the three steps below:

1 ) Remove all the return specifications from all methods from this package:

` public function exemple( ): return_specification { ... }`  **to** `public function exemple( ) { ... }`

2 ) Change all the methods inputs that was specified as **int** or as **string**:

`public function exemple(string input, int input2 ) { ... }` **to** `public function exemple(input, input2 ) { ... }`

3 ) Change all instances of one line if:
`$exemple ?? $output_else` **to** `$exemple ? $exemple  : $output_else`
