### ISSUE TITLE
Analytics::fetchVisitorsAndPageViews() should not be called statically

### ISSUE THREAD

**Issue by macikgoz25** [spatie/laravel-analytics#168]
Hello Sir I have a problem. I'm using Laravel 5.4 on vagrant (php v7) I try this code but throw an Exception.

use Spatie\Analytics\Analytics;
use Spatie\Analytics\Period;
$analyticsData = Analytics::fetchVisitorsAndPageViews(Period::days(7));

Non-static method Spatie\Analytics\Analytics::fetchVisitorsAndPageViews() should not be called statically

**Comment by freekmurze** [comment]
You should import the facade.

Change

```php
use Spatie\Analytics\Analytics;
```

to 

```php
use Analytics;
```

**Comment by CrixuAMG** [comment]
If this is wrong, update the documentation please.

**Comment by freekmurze** [comment]
@CrixuAMG If you spot errors in the readme, send a PR to correct them

**Comment by juliangums** [comment]
Fell for it too. Updated readme https://github.com/spatie/laravel-analytics/pull/250

**Comment by CrixuAMG** [comment]
Thanks @juliangums for the quick fix!

**Comment by GigaMick** [comment]
Hi, I have done everything according to the docs but the alias is not found.

I am using laravel 5.6 and although it says the facade should be automatically setup, it wasn't working so I also added this manually:

```
        'Analytics' => Spatie\Analytics\AnalyticsFacade::class,
```

but it is still telling me that
```
use Analytics
```

is not working. Any ideas? @freekmurze 

Thanks in advance

**Comment by reubenwedson** [comment]
> Hi, I have done everything according to the docs but the alias is not found.
> 
> I am using laravel 5.6 and although it says the facade should be automatically setup, it wasn't working so I also added this manually:
> 
> ```
>         'Analytics' => Spatie\Analytics\AnalyticsFacade::class,
> ```
> 
> but it is still telling me that
> 
> ```
> use Analytics
> ```
> 
> is not working. Any ideas? @freekmurze
> 
> Thanks in advance

use Spatie\Analytics\AnalyticsFacade as Analytics
