### ISSUE TITLE
Error refreshing the OAuth2 token, Google_Auth_Exception in OAuth2.php

### ISSUE THREAD

**Issue by niknackster** [spatie/laravel-analytics#172]
I am using PHP 5.6.19 and Laravel-Analytics V1 to call google analytics API

I have set config file with required credentials and P12 key file location.

now I am trying to call real time API 
$analyticsData = LaravelAnalytics::getActiveUsers();

but getting below response
Google_Auth_Exception in OAuth2.php line 364:
Error refreshing the OAuth2 token, message: '{
"error" : "invalid_grant",
"error_description" : "Invalid JWT Signature."
}'

I have googled about this error... I have also checked my share hosting servers time which is in sync with NTP server already still getting this error.  not getting any solution. Please help me. 
As I am using shared hosting I can't upgrade to PHP 7 and use the latest package.

**Comment by sebastiandedeyne** [comment]
Are your still experiencing this issue?
