### ISSUE TITLE
Could not resolve host: accounts.google.com

### ISSUE THREAD

**Issue by Siphion01** [spatie/laravel-analytics#173]
Hi, receiving this error when trying to run following method.

Code:

`fetchVisitorsAndPageViews(object(Period))`

Error:

```
Google_IO_Exception in Curl.php line 126:
Could not resolve host: accounts.google.com

```
Confirmed working a few days back, now this error.  It's happening on another sandbox L5 app I'm working on too.

Steps:

Ping tested accounts.google.com - Working
Lynx accounts.google.com - Working
JSON Credentials - Confirmed Accurate

**Comment by ldominguezc** [comment]
Anything?
