### ISSUE TITLE
Composer says: "Your requirements could not be resolved to an installable set of packages."

### ISSUE THREAD

**Issue by imannms** [spatie/laravel-analytics#177]
`$ php -c php.ini composer.phar require spatie/laravel-analytics`

Using version ^1.4 for spatie/laravel-analytics
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install spatie/laravel-analytics 1.4.1
    - Conclusion: remove google/apiclient v2.1.3
    - Installation request for spatie/laravel-analytics ^1.4 -> satisfiable by spatie/laravel-analytics[1.4.0, 1.4.1].
    - Conclusion: don't install google/apiclient v2.1.3
    - spatie/laravel-analytics 1.4.0 requires google/apiclient 1.1.* -> satisfiable by google/apiclient[1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, v1.1.8].
    - Can only install one of: google/apiclient[1.1.1, v2.1.3].
    - Can only install one of: google/apiclient[1.1.2, v2.1.3].
    - Can only install one of: google/apiclient[1.1.3, v2.1.3].
    - Can only install one of: google/apiclient[1.1.4, v2.1.3].
    - Can only install one of: google/apiclient[1.1.5, v2.1.3].
    - Can only install one of: google/apiclient[1.1.6, v2.1.3].
    - Can only install one of: google/apiclient[1.1.7, v2.1.3].
    - Can only install one of: google/apiclient[v1.1.8, v2.1.3].
    - Installation request for google/apiclient (locked at v2.1.3) -> satisfiable by google/apiclient[v2.1.3].

Installation failed, reverting ./composer.json to its original content.

**Comment by freekmurze** [comment]
Could you try this in a vanilla Laravel project?
