### ISSUE TITLE
Please update the README.

### ISSUE THREAD

**Issue by yuhua-chen** [spatie/laravel-analytics#178]
The service provider should be like this:
```
// config/app.php
'providers' => [
    ...
    Spatie\LaravelAnalytics\LaravelAnalyticsServiceProvider::class
    ...
];
```

**Comment by sebastiandedeyne** [comment]
If your installation includes `LaravelAnalyticsServiceProvider` you're using the previous version of the package, which also has an older readme: https://github.com/spatie/laravel-analytics/blob/88eb75beadcd8dade2f3ee2423f3716253b2104d/README.md

I'll add a link to the current readme.
