### ISSUE TITLE
google/apiclient

### ISSUE THREAD

**Issue by qamarxaman** [spatie/laravel-analytics#179]
Hi

I like your project but I can see that "google/apiclient" is updated to "google/apiclient:^2.0". Can you update it here too, if its not so hard to do that.

Qamar, Denmark

**Comment by sebastiandedeyne** [comment]
The new client is part of v3 of this package which hasn't been released yet. If you need this asap, require a commit hash from the v3 branch for now as it's stable according to users, but we might do some more breaking changes before the actual release.

See this issue: https://github.com/spatie/laravel-analytics/issues/125
