### ISSUE TITLE
Request doesn't works

### ISSUE THREAD

**Issue by Mdpproduction** [spatie/laravel-analytics#18]
Hi,
i followed the instructions for this package. But when i execute a simple request i get this message:

"Error refreshing the OAuth2 token, message: '{
"error" : "invalid_grant"
}'"

What mean ?

**Comment by MatthiasDeWinter** [comment]
I think you forgot to include ga: before your key!

**Comment by Mdpproduction** [comment]
Ok, i'll try again. Thanks
