### ISSUE TITLE
Getting Google_Service_Analytics_GaData objects from performQuery

### ISSUE THREAD

**Issue by rodericktech** [spatie/laravel-analytics#181]
First of all, thanks so much for developing this software! It is incredibly convenient for many uses.
This issue is similar to #146, but when I attempt the same solution, I get an empty collection.

This code:
````
    $twelveMonthsData = Analytics::performQuery(Period::create($yearAgo, $today), 'ga:sessions', ['dimensions' => 'ga:month']);
    dd($twelveMonthsData);
````

Returns this object (with the correct / expected data, not expanded for privacy reasons):
````
Google_Service_Analytics_GaData {#258 ▼
  #collection_key: "rows"
  #columnHeadersType: "Google_Service_Analytics_GaDataColumnHeaders"
  #columnHeadersDataType: "array"
  +containsSampledData: false
  +dataLastRefreshed: null
  #dataTableType: "Google_Service_Analytics_GaDataDataTable"
  #dataTableDataType: ""
  +id: "https://www.googleapis.com/analytics/v3/data/ga?ids=ga:19778070&dimensions=ga:month&metrics=ga:sessions&start-date=2016-05-03&end-date=2017-05-03"
  +itemsPerPage: 1000
  +kind: "analytics#gaData"
  +nextLink: null
  +previousLink: null
  #profileInfoType: "Google_Service_Analytics_GaDataProfileInfo"
  #profileInfoDataType: ""
  #queryType: "Google_Service_Analytics_GaDataQuery"
  #queryDataType: ""
  +rows: array:12 [▶]
  +sampleSize: null
  +sampleSpace: null
  +selfLink: "https://www.googleapis.com/analytics/v3/data/ga?ids=ga:19778070&dimensions=ga:month&metrics=ga:sessions&start-date=2016-05-03&end-date=2017-05-03"
  +totalResults: 12
  +totalsForAllResults: array:1 [▶]
  #internal_gapi_mappings: []
  #modelData: array:3 [▶]
  #processed: []
}
````

So far, so good.  I now have the data in some format.  But when I run this:
````
    $sessionsTwelveMonths = collect($twelveMonthsData);
    dd($sessionsTwelveMonths);
````

I get an empty collection:
````
Collection {#167 ▼
  #items: []
}
````

I couldn't find information in the documentation about what to do if one of these objects is returned and it fails to be collected.  (Using Laravel 5.4, PHP 7)  Is there a simple way to turn a Google_Service_Analytics_GaData object into JSON, a PHP array, or something similarly 'universal'?  Just not sure what methods to call to facilitate processing / display if it can't morph into a collection directly.  Thanks for any reply!  I apologize if I missed something in the documentation that covered this.

**Comment by freekmurze** [comment]
Try this: `dd($twelveMonthsData->rows);`
