### ISSUE TITLE
Update to Reporting API v4?

### ISSUE THREAD

**Issue by nomadme** [spatie/laravel-analytics#182]
Any plan to updating to Google Analytics Reporting API v4?

**Comment by freekmurze** [comment]
Currently not, but I might create a new major version of this package somewhere early 2018.

If you want it sooner it accept a fully tested PR that upgrades te packages to use v4 using a similar API as the current one. Breaking changes allowed if needed.

**Comment by nomadme** [comment]
Thanks for the package.
