### ISSUE TITLE
How can I change the client_email for the service account key credential to my own email ?

### ISSUE THREAD

**Issue by jpfernandezl** [spatie/laravel-analytics#184]
Hello,

I would like to use an email with my own domain
instead of
@xxxx.iam.gserviceaccount.com

How can I do that? The problem is that there is another app that is using an email with my own domain
and I can not ask users to give access to another email.

Thanks

**Comment by freekmurze** [comment]
Seems like this question is not relevant to this package. 

Try looking for an answer at the [Google developers site](https://developers.google.com/.)
