### ISSUE TITLE
  [Symfony\Component\Debug\Exception\FatalErrorException]   Class 'App\Providers\View' not found. I need helpppp !!!. The problem happen when I run php composer.phar update 

### ISSUE THREAD

**Issue by DiploNavy** [spatie/laravel-analytics#185]

**Comment by DiploNavy** [comment]
![image](https://cloud.githubusercontent.com/assets/15154030/26275306/7b89d392-3d87-11e7-8d00-5b984828b878.png)

**Comment by freekmurze** [comment]
This problem is not related to the package.

Reopen if this problem occurs when installing the package in a vanilla Laravel app
