### ISSUE TITLE
Is there any way to send POST request?

### ISSUE THREAD

**Issue by buiminhduc** [spatie/laravel-analytics#189]
Hi,
For now, I can see Laravel Analytics is using GET request to send query to Google Analytics, but I am wondering if we can change or set the request type in config? I need to send POST request to Google Analytics because my application is using filter, and the filter is using too long text so it exceeds max length of GET request.
Thanks.

**Comment by freekmurze** [comment]
You can construct any query you with by using the underlying service.

https://github.com/spatie/laravel-analytics#all-other-google-analytics-queries
