### ISSUE TITLE
It shows fatal error

### ISSUE THREAD

**Issue by islamjaidul** [spatie/laravel-analytics#190]
<img width="597" alt="screen shot 2017-06-16 at 2 34 47 pm" src="https://user-images.githubusercontent.com/11510256/27218742-0dab3148-52a1-11e7-81dc-b6467de1b52b.png">

The setup has completed as stated in the documentation. But it seems fatal error when included the code snippet in the controller.

`      
       $analyticsData = Analytics::fetchVisitorsAndPageViews(Period::days(7));
       return $analyticsData;
`

Use used the php version 7.1.

**Comment by freekmurze** [comment]
Pretty sure you are not using PHP 7. Run `phpinfo();` in your script to know for sure.
