### ISSUE TITLE
Non-service account support?

### ISSUE THREAD

**Issue by judgej** [spatie/laravel-analytics#191]
I couldn't see this in the docs, but I may just be missing it.

I would like the current user to authorise their own Google account, so my application can access statistics on their site rather than my own site. This would include renewal tokens so the application can continue to fetch data with the user(s) not present.

Is this supported by this package? Or is it a use-case that is out of scope?

**Comment by freekmurze** [comment]
Currently that is not supported by this package. As I don't need this functionality myself I don't plan adding this.

However if the solution is simple, non-breaking and well tested I'd consider accepting a PR that adds this to the package.

**Comment by judgej** [comment]
I thought that may be the case. I've started putting a stand-alone package together to authorise a Google API account, so will run from that as a complementary package. If there is a way to merge them later, then I can look at that, but it will probably be just as well to keep them separate.
