### ISSUE TITLE
curl error 60

### ISSUE THREAD

**Issue by metinbulak** [spatie/laravel-analytics#193]
thank you for laravel-analytics 
I use analytics in localhost and I get this error cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

can anyone help me.

**Comment by tallrye** [comment]
Hi,

Please see: https://github.com/google/google-api-php-client/issues/843 

Hope this helps.

**Comment by freekmurze** [comment]
Closing this as the problem is probably more related to google-api-php
