### ISSUE TITLE
spatie/laravel-analytics performQuery error

### ISSUE THREAD

**Issue by metinbulak** [spatie/laravel-analytics#194]
I use spatie laravel google analytics with no error but when I use $analyticsData = Analytics::performQuery($per,'ga:sessions',$dimen); I get this error htmlspecialchars() expects parameter 1 to be string, object given ... 
how can I use Analytics::performQuery ?

 all my code are 

$startDate = Carbon::now()->subYear();
   $endDate = Carbon::now();

   $per=Period::create($startDate, $endDate);
   $dimen=['dimensions' => 'ga:browser'];

   $analyticsData = Analytics::performQuery($per,'ga:sessions',$dimen);

please anyone help me
thanks

**Comment by vesper8** [comment]
Your code worked for me

```
            $startDate = Carbon::now()->subWeeks(1);
            $endDate = Carbon::now();

            $period = Period::create($startDate, $endDate);
            $dimen = ['dimensions' => 'ga:browser'];

            $analyticsData = Analytics::performQuery($period, 'ga:sessions', $dimen);
            ddd($analyticsData->getRows());
```
