### ISSUE TITLE
Could not find a credentials file at `C:\xampp\htdocs\moonbao-dev\storage\app/analytics/service-account-credentials.json`.

### ISSUE THREAD

**Issue by sumanghimirey** [spatie/laravel-analytics#197]

**Comment by freekmurze** [comment]
I guess the problem is caused by the wrong slashes. Try to correct that.

**Comment by faizy7sheikh** [comment]
SchulzeFelix\BigQuery\Exceptions\InvalidConfiguration
Could not find a credentials file at ``.

Help me plz

**Comment by lovecoding-git** [comment]
@sumanghimirey 
Did you put service-account-credentials.json file in storage/app/analytics?
