### ISSUE TITLE
Laravel v5.3.31 boilerplate 

### ISSUE THREAD

**Issue by StefyZ** [spatie/laravel-analytics#198]
unable to install the package 

tried to run: 

composer require spatie/laravel-analytics

Getting this error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.3.31
    - Conclusion: don't install laravel/framework v5.3.31
    - spatie/laravel-analytics 3.0.0 requires illuminate/contracts ~5.4.0 -> satisfiable by illuminate/contracts[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.9].
    - spatie/laravel-analytics 3.0.1 requires illuminate/contracts ~5.4.0 -> satisfiable by illuminate/contracts[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.9].
    - don't install illuminate/contracts v5.4.0|don't install laravel/framework v5.3.31
    - don't install illuminate/contracts v5.4.13|don't install laravel/framework v5.3.31
    - don't install illuminate/contracts v5.4.17|don't install laravel/framework v5.3.31
    - don't install illuminate/contracts v5.4.19|don't install laravel/framework v5.3.31
    - don't install illuminate/contracts v5.4.27|don't install laravel/framework v5.3.31
    - don't install illuminate/contracts v5.4.9|don't install laravel/framework v5.3.31
    - Installation request for laravel/framework (locked at v5.3.31, required as 5.3.*) -> satisfiable by laravel/framework[v5.3.31].
    - Installation request for spatie/laravel-analytics ^3.0 -> satisfiable by spatie/laravel-analytics[3.0.0, 3.0.1].

Anyone found a resolution for this?

**Comment by freekmurze** [comment]
Version 3 of this package has L5.3 compatiblity.
