### ISSUE TITLE
Extend "Analytics" Class

### ISSUE THREAD

**Issue by sarotnem** [spatie/laravel-analytics#199]
I can't manage to properly extend the Analytics class. The problem I have is how to implement the ServiceProvider.

**App\CustomAnalytics.php**

```
<?php

namespace App\Analytics;
use Analytics;

class CustomAnalytics extends Analytics
{
	public function test() 
        {
		return "It works!";
	}
}
```

**App\Providers\CustomAnalyticsServiceProvider.php**
```
<?php

namespace App\Providers;

use Spatie\Analytics\AnalyticsServiceProvider;

class CustomAnalyticsServiceProvider extends AnalyticsServiceProvider
{
    /**
     * Bootstrap the application services.
     *
     * @return void
     */
    public function boot()
    {
        //
    }

    /**
     * Register the application services.
     *
     * @return void
     */
    public function register()
    {
        //What must be inserted here?
    }
}
```

Of course if I call CustomAnalytics::hello() I get that Non-static method App\Analytics\CustomAnalytics::test() should not be called statically.

**Comment by sebastiandedeyne** [comment]
If you want to call your class in a static-like way you'll need to create a facade.

You can refer to the Laravel docs for a detailed explanation on what they are and how to make them.

https://laravel.com/docs/5.5/facades
