### ISSUE TITLE
siteId format

### ISSUE THREAD

**Issue by pabloacevedo** [spatie/laravel-analytics#20]
Hi, my siteId have this format UA-xxxxxxxx-x and when call to api, show me that error.

(400) Invalid value 'UA-xxxxxxxx-x'. Values must match the following regular expression: 'ga:[0-9]+'

**Comment by freekmurze** [comment]
The UA-code isn't the siteId this package needs.

To find the right value for siteId log in to Google Analytics go the the Admin section. In the property-column select the website name of which you want to retrieve data, then click View Settings in the View-column. The value presented as View Id prepended with 'ga:' can be used as siteId.

Please refer to the readme to find instructions on how to configure this package.
