### ISSUE TITLE
Loading credentials JSON file from an external disk

### ISSUE THREAD

**Issue by luckyrabbitllc** [spatie/laravel-analytics#200]
My app is hosted on Heroku, which requires the use of external file storage (S3, Google, Dropbox, etc). 

However, it seems that this sort of setup is incompatible with this package at the moment, as it triggers the  `guardAgainstInvalidConfiguration` exception, which I think must be because it checks for the existence of the json file using php's native `file_exists` function, not the app's configured storage driver.

How might I go about overriding this so that I can access my json from my external disk?

**Comment by sebastiandedeyne** [comment]
Even if you'd pass the guard, does the Google library actually support that? Here's where we use the path: https://github.com/spatie/laravel-analytics/blob/9128d68f7ce6769cb7715783a817c81c381f4ffe/src/AnalyticsClientFactory.php#L29

**Comment by luckyrabbitllc** [comment]
If I'm correct, it appears that for the PHP library, this is the relevant portion:

(from https://developers.google.com/analytics/devguides/reporting/core/v3/quickstart/service-php)

`function initializeAnalytics()
{
  // Creates and returns the Analytics Reporting service object.

  // Use the developers console and download your service account
  // credentials in JSON format. Place them in this directory or
  // change the key file location if necessary.
  $KEY_FILE_LOCATION = __DIR__ . '/service-account-credentials.json';

  // Create and configure a new client object.
  $client = new Google_Client();
  $client->setApplicationName("Hello Analytics Reporting");
  $client->setAuthConfig($KEY_FILE_LOCATION);
  $client->setScopes(['https://www.googleapis.com/auth/analytics.readonly']);
  $analytics = new Google_Service_Analytics($client);

  return $analytics;
}`

So, to me this means it must be possible to override the value in this line

`  $client->setAuthConfig($KEY_FILE_LOCATION);`

 to point to a url. But I'm not sure how to go about doing that within the context of this package.

Or perhaps there's a better way to solve this problem? I know I can't be the only one running an app with the combination of Google Analytics + Heroku - surely this has come up before, but I'm not educated enough in the realm of packages + Heroku's statelessness requirements to know how to solve this or even search for the solution to this problem.

**Comment by luckyrabbitllc** [comment]
Update: 

I've solved this by calling a 'syncCredentials' command before every analytics call which pulls the remote file and writes a copy to local storage at the path hardcoded in the analytics.php config file. 

Not ideal, but it works for now.

**Comment by lovecoding-git** [comment]
@startupengine 
How did you do it?
