### ISSUE TITLE
Impossible depuis le composer

### ISSUE THREAD

**Issue by Cedcomps** [spatie/laravel-analytics#201]
Cela me donne l'erreur suivante: 
```
 [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Spatie\Analytics\AnalyticsServiceProvider' not found
```

`Script php artisan optimize handling the post-update-cmd event returned with error code 255`

`Installation failed, reverting ./composer.json to its original content.`

**Comment by sebastiandedeyne** [comment]
Have you registered the service provider as described in the installation guide?

https://github.com/spatie/laravel-analytics#installation

**Comment by Cedcomps** [comment]
Yep of course but this error appear during the installation in composer with 
`composer require spatie/laravel-analytics`

**Comment by sebastiandedeyne** [comment]
Composer pulled in v1 of this package, you'll need to check out an older readme file for installation instructions.

https://github.com/spatie/laravel-analytics/blob/88eb75beadcd8dade2f3ee2423f3716253b2104d/README.md

**Comment by Cedcomps** [comment]
Hum i don't understand ... Sorry i'm still news in laravel, but I have 5.4 framework and I try to add like the other package into composer

**Comment by sebastiandedeyne** [comment]
You could manually change the version to `^3.0` there, run `composer update` and see which package versions are colliding.

Feel free to share your `composer.json`'s contents and I'll have a look :)
