### ISSUE TITLE
Class 'App\Http\Controllers\Analytics' not found

### ISSUE THREAD

**Issue by robertnicjoo** [spatie/laravel-analytics#202]
I get the error of `Class 'App\Http\Controllers\Analytics' not found` after fresh installation.

this is my function:

```
public function index() {
      $analyticsData = Analytics::fetchVisitorsAndPageViews(Period::days(7));
      return view('analytics.index', compact('analyticsData'));
    }
```

What should I do?

**Comment by freekmurze** [comment]
You probably forgot to import the facade.

Add

```
use Analytics;
```

at the top of your class.

**Comment by robertnicjoo** [comment]
Thanks man. now i get `Class 'App\Http\Controllers\Period' not found` error.

**Comment by freekmurze** [comment]
You forget to import the namespace where `Period` resides in.

**Comment by robertnicjoo** [comment]
@freekmurze Sorry for all my questions this is my full controller code:

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Carbon\Carbon;
use Analytics;
use Spatie\Analytics\Period;

class AnalyticsController extends Controller
{

    public function __construct() {
        $this->middleware(['auth', 'isAdmin']);
    }

    public function index() {
      $analyticsData = Analytics::fetchMostVisitedPages(Period::days(7));
      return view('analytics.index', compact('analyticsData'));
    }

}
```
 
I ave no error but also no view! just white page.

**Comment by Bippper** [comment]
The use statement with non-compound name 'Analytics' has no effect

New Error -_-

**Comment by sebastiandedeyne** [comment]
You don't need a `use` statement if you're code isn't in a namespace.

**Comment by robertnicjoo** [comment]
now someone please give me straight answer! someone says use statement, someone says don't confuse man! please just provide me the code i should import in my controller.


Thank you all.

**Comment by sebastiandedeyne** [comment]
@robertnicjoo What Laravel & package versions are you using?

**Comment by robertnicjoo** [comment]
@sebastiandedeyne 5.5

**Comment by sebastiandedeyne** [comment]
And the exact package version you have installed? (you can see that with `composer show`)

**Comment by robertnicjoo** [comment]
```html
spatie/laravel-analytics                 3.2.0   A Laravel 5 package to retrieve Google Analytics data.
```

**Comment by sebastiandedeyne** [comment]
> I ave no error but also no view! just white page.

So the `Class Period not found` error is gone right?

In that case, judging by your code you're using our code correctly. If you can't provide a meaningful error trace, we can't really help you any further.

You could look in your application logs for errors if you're seeing a white page. Otherwise I'd recommend posting on the Laracasts forums or StackOverflow for some general PHP debugging help in your case, as this isn't an issue with our package.

https://laracasts.com/discuss

**Comment by robertnicjoo** [comment]
@sebastiandedeyne I'm trying it again in fresh project and I recieve this error

```
{"error":{"errors":[{"domain":"global","reason":"insufficientPermissions","message":"User does not have any Google Analytics account."}],"code":403,"message":"User does not have any Google Analytics account."}}
```

why is that?

**Comment by sebastiandedeyne** [comment]
Please follow our permissions guide in the readme.

https://github.com/spatie/laravel-analytics#granting-permissions-to-your-analytics-property

**Comment by robertnicjoo** [comment]
I've done that already 

![678](https://user-images.githubusercontent.com/8672823/32365436-71634f76-c0ac-11e7-8a9d-f3fb5afb1212.png)

**Comment by robertnicjoo** [comment]
I think the problem comes from this part
![role](https://user-images.githubusercontent.com/8672823/32365807-004a2204-c0ae-11e7-8374-995aaf93178b.png)

In documents here has no mention about choosing role which i think is new! so which role i have to choose here? because i'm getting role error right?
```
"reason":"insufficientPermissions"
```

**Comment by sebastiandedeyne** [comment]
This is something new, so don't really know the answer for sure... Project sounds like a sensible value.

**Comment by cromartie1984** [comment]
i had the same error : **Class 'App\Http\Controllers\Period' not found error.**
i resolved this by adding  **use Spatie\Analytics\Period;**

**Comment by pawanchhapola** [comment]
On the controller use below namespaces:-

use Illuminate\Support\Collection;
use Analytics;
use Spatie\Analytics\Period;
