### ISSUE TITLE
Call to undefined method Spatie\LaravelAnalytics\LaravelAnalytics::getSessions()

### ISSUE THREAD

**Issue by jcobhams** [spatie/laravel-analytics#203]
I've been using this package for over a year now and just recently i started migrating to heroku.com server, and i get the error;  **_FatalThrowableError in Facade.php line 219:
Call to undefined method Spatie\LaravelAnalytics\LaravelAnalytics::getAllSessions()_**

here's my code:

`<?php`

`namespace App\Http\Controllers\admin;`

`use App\Http\Controllers\Controller;`
`use App\Payments\Payment;`
`use Carbon\Carbon;`
`use Spatie\LaravelAnalytics\LaravelAnalyticsFacade as LaravelAnalytics;`
`//use Spatie\LaravelAnalytics\LaravelAnalytics as LaravelAnalytics`

`class DashboardController extends Controller`
`{`
`    public function index()`
`    {`
`$stats= LaravelAnalytics::getVisitorsAndPageViews(10)->toArray();`
`        $todaySessions = LaravelAnalytics::getSessions(Carbon::today(), Carbon::now())->toArray();`
`        $allSessions = LaravelAnalytics::getSessions(Carbon::create(2016,9,9), Carbon::now())->toArray();`
`        $allSessionsData = LaravelAnalytics::getAllSessions(Carbon::create(2016,9,9), Carbon::now())->toArray()[0];`

**Comment by freekmurze** [comment]
Probably this is caused by you running a different version of PHP on your server. Use `composer show` to determine if the right version of the package is being pulled in.

**Comment by jcobhams** [comment]
I've used `composer show` i have the same versions of the package, both locally, on my old server and on the new server but this issue is just on the new one.

**Comment by jcobhams** [comment]
The issue is still persistent.
