### ISSUE TITLE
Batch queries

### ISSUE THREAD

**Issue by extra90** [spatie/laravel-analytics#21]
Can you provide additional method for batch queries?
Thanks

**Comment by freekmurze** [comment]
I'm not sure what you mean. Feel free to submit a pull request.

**Comment by extra90** [comment]
I mean that I could perform multiple custom queries at once.

**Comment by freekmurze** [comment]
Currently we have no need for this functionality. But if you provide the necessary changes via a pull request I'll happily merge it.
