### ISSUE TITLE
[SOLVED ]Some problem with php version

### ISSUE THREAD

**Issue by ardakocaktr** [spatie/laravel-analytics#212]
php version is 7.1.3 on my vagrant and this package says php : ^7.0  but i cant install last version of this package. why??

It throws that error : 

spatie/laravel-analytics 3.0.1 requires php ^7.0 -> your PHP version (7.1.3-3+deb.sury.org~xenial+1) overridden by "config.platform.php" version (5.6.4) does not satisfy that requirement.

Edit : 

Uhh I just noticed that . Platform php version was 5.6.4 in my composer.json and I've changed it to my actual php version. It worked now

**Comment by freekmurze** [comment]
This probably caused by the Laravel installer which recently started to add a `platform` key to `composer.json`. Remove that `platform` key and try installing the package again.

**Comment by hadi77makkawi** [comment]
Is it possible to install this package on PHP  (7.0.28) 😕 ?
