### ISSUE TITLE
Support for Laravel 5.5?

### ISSUE THREAD

**Issue by rattfieldnz** [spatie/laravel-analytics#217]
Hi there,

With the very recent official release of Laravel 5.5 (https://laravel-news.com/laravel-5-5), what kind of support for this package will be provided for Laravel 5.5, or what changes to the package will be needed? I am working on a Laravel project (that uses this package) at the moment, and I expect it to be using Laravel 5.5 on beta/preview release. I'm prepared to hold off upgrading my project to Laravel 5.5 (from 5.4) until this package fully supports it - it really is a good package I'd like to keep :).

**Comment by freekmurze** [comment]
You can already use the `laravel-55` branch in your project.

I'm planning on tagging a new stable release that's compatible with Laravel 5.5 very soon.
