### ISSUE TITLE
composer: Failed to execute unzip -qq

### ISSUE THREAD

**Issue by sixty8** [spatie/laravel-analytics#220]
- Installing google/apiclient-services (v0.23): Loading from cache
    Failed to execute unzip -qq

**Comment by freekmurze** [comment]
I'm thinking this problem does not concern this package. It's probably caused by unzip being unavailable on your system.

**Comment by Schrank** [comment]
Stumbled over this issue, maybe this helps future viewer: I assume this happens due to homebrew installed unzip.
