### ISSUE TITLE
Issue while installing.

### ISSUE THREAD

**Issue by krishna8723** [spatie/laravel-analytics#223]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-analytics ^3.1 -> satisfiable by spatie/laravel-analytics[3.1.0].
    - Conclusion: remove laravel/framework v5.1.46
    - Conclusion: don't install laravel/framework v5.1.46
    - spatie/laravel-analytics 3.1.0 requires illuminate/contracts ~5.4.0|~5.5.0 -> satisfiable by illuminate/contracts[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.2].
    - don't install illuminate/contracts v5.4.0|don't install laravel/framework v5.1.46
    - don't install illuminate/contracts v5.4.13|don't install laravel/framework v5.1.46
    - don't install illuminate/contracts v5.4.17|don't install laravel/framework v5.1.46
    - don't install illuminate/contracts v5.4.19|don't install laravel/framework v5.1.46
    - don't install illuminate/contracts v5.4.27|don't install laravel/framework v5.1.46
    - don't install illuminate/contracts v5.4.36|don't install laravel/framework v5.1.46
    - don't install illuminate/contracts v5.4.9|don't install laravel/framework v5.1.46
    - don't install illuminate/contracts v5.5.0|don't install laravel/framework v5.1.46
    - don't install illuminate/contracts v5.5.2|don't install laravel/framework v5.1.46
    - Installation request for laravel/framework == 5.1.46.0 -> satisfiable by laravel/framework[v5.1.46].

**Comment by freekmurze** [comment]
The latest version of this package is only installable in L5.5
