### ISSUE TITLE
Return 0 total results

### ISSUE THREAD

**Issue by musadeq** [spatie/laravel-analytics#227]
Hello, my total results is 0, but i try check in [https://ga-dev-tools.appspot.com/query-explorer/](https://ga-dev-tools.appspot.com/query-explorer/) and give me normal results. I don't know what the problem, so i randomly change the code like : i remove space between comma in array dimmension, and it's give me normal results. But the next day, it will give me 0 results, and i do it again, i change random code like `'start-index' => (int)$index`, and give me normal results. And yes, in the next day it will happen again, i change `(int)` to `(string)` and give me normal results. And untill today it's still the same.

I know it to be normal not caused by changed my code, and the problem is not in comma, adding `(int)` or `(string)`, etc. I only don't have any idea to description this error to you. Maybe you can solve the problem that happened, and maybe it will give a little clue for you.

```
$analyticsData = LaravelAnalytics::setSiteId($this->pub_view_id)->performQuery($start, $end, "ga:uniquePageviews, $a,$b, $c", [
                'dimensions' => "$d,$e,$f",
                'start-index' => $index
            ]);

```
Sorry my english so bad. 
Thanks.

**Comment by introwit** [comment]
The syntax is wrong. Correct usage is in the docs (here)[https://github.com/spatie/laravel-analytics#usage]
