### ISSUE TITLE
The use statement with non-compound name 'Analytics' has no effect

### ISSUE THREAD

**Issue by Bippper** [spatie/laravel-analytics#230]
The use statement with non-compound name 'Analytics' has no effect

**Comment by freekmurze** [comment]
Could you share the code that is causing you trouble? Pretty sure this is caused by something in your app and not by this package.

**Comment by Bippper** [comment]
my web
<?php

use Spatie\Analytics\Period;
use Carbon\Carbon;
use Spatie\LaravelAnalytics\LaravelAnalyticsFacade as LaravelAnalytics;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/data', function () {
$analyticsData = Analytics::fetchVisitorsAndPageViews(Period::days(7));
dd($analyticsData );
});

**Comment by freekmurze** [comment]
I'm thinking that in your code you don't use a namespace. If that's the case you don't need to add `use Analytics;` at the top of the file.
