### ISSUE TITLE
Dumb kid here! Google_Service_Exception (400)

### ISSUE THREAD

**Issue by Bippper** [spatie/laravel-analytics#231]
{ "error": "invalid_grant", "error_description": "Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems." }
,
I solve the 1st one by upgrading to laravel 5.5

**Comment by freekmurze** [comment]
So... the problem is solved?

**Comment by Bippper** [comment]
nope!, what i mean is the last one i ask is solve i just upgraded my laravel. then there's this help master

**Comment by n2ray** [comment]
I'm on centos 6, I solved this with:

`# service ntpd stop`
`# ntpd -gq`
`# service ntpd start`
