### ISSUE TITLE
how to use google oauth to access view id ?

### ISSUE THREAD

**Issue by saeedvir** [spatie/laravel-analytics#235]
how to use google oauth to access view id ?

my website --> user login with google analytics account (OAUTH 2) --> get user google analytics view id --> report ( for ex: get pageviews)

**Comment by AlexVanderbist** [comment]
Hi @saeedvir 

By default this package will only work with the API credentials provided in the `.env` and `service_account_credentials_json` files.

You can instanciate your own `AnalyticsClient` with the user's credentials configured like this: 
```php
   $analyticsConfig = [
       // see the actual config file for what goes in here
   ];
   $analyticsClient = AnalyticsClientFactory::createForConfig($analyticsConfig);
   $analytics = new Analytics($analyticsClient, $analyticsConfig['view_id']);
```

**Comment by OctaneInteractive** [comment]
Hi @AlexVanderbist, could you provide a better example?

I don't understand how that would work with the code examples on the home page.
