### ISSUE TITLE
[Bugish] Caches the config too early preventing interaction first.

### ISSUE THREAD

**Issue by OwenMelbz** [spatie/laravel-analytics#236]
Hi,

We've identified an issue within the `AnalyticsServiceProvider.php` which it does

```php
        $analyticsConfig = config('analytics');

        $this->app->bind(AnalyticsClient::class, function () use ($analyticsConfig) {
            return AnalyticsClientFactory::createForConfig($analyticsConfig);
        });

        $this->app->bind(Analytics::class, function () use ($analyticsConfig) {
            $this->guardAgainstInvalidConfiguration($analyticsConfig);

            $client = app(AnalyticsClient::class);

            return new Analytics($client, $analyticsConfig['view_id']);
        });
```

You take a copy of the `config` whilst the application is booting - this means that if theres any middleware, or other services etc that interact with the application config - they get disregarded.

An example would be, if you were running an application where users have their own dashboard that requires a different view id, the user is not authenticated until the session middleware has loaded - by this time the package has already cached a `$view_id = null` which then throws the `InvalidConfiguration::viewIdNotSpecified` exception.

If you were to make sure the config was loaded from within the closure - it would pull the config when it is needed - allowing you to interact with configurations e.g

```php
        $this->app->bind(AnalyticsClient::class, function () use ($analyticsConfig) {
            $analyticsConfig = config('analytics');
            
            return AnalyticsClientFactory::createForConfig($analyticsConfig);
        });
```

Moving it to within the closure makes sure that the config data it receives is completely handled before passing it to the analytic clients etc.

Would this be something you'd consider merging to fix this issue?

Thanks

**Comment by freekmurze** [comment]
Thanks for your detailed explanation. Yes, I'd probably merge the PR that changes this.

**Comment by OwenMelbz** [comment]
@freekmurze hey - just wondering if theres a release cycle ETA on these to be tagged as packagist ist still only showing the current version :)

Thanks

**Comment by OwenMelbz** [comment]
@freekmurze poke :D

**Comment by freekmurze** [comment]
v3.4.0 includes the latest changes, no?
