### ISSUE TITLE
How to get amount of active users by hour the last 24 hours?

### ISSUE THREAD

**Issue by exzib** [spatie/laravel-analytics#237]
How do I get the amount of active users by the other the past 24 hours?

Currently I use this:

    $online = Analytics::getAnalyticsService()->data_realtime->get('ga:idhere',  'rt:activeVisitors')->totalsForAllResults['rt:activeVisitors'];

And it returns how many are online right now, but im not sure how to get an array of the last 24 hours ´?

**Comment by freekmurze** [comment]
The package doesn't implement a dedicated method for that. Best to look it up somewhere in the google docs or ask it on a google related forum.
