### ISSUE TITLE
Check if analytics connection is possible 

### ISSUE THREAD

**Issue by mattmorgante** [spatie/laravel-analytics#238]
Hello Spatie, 

First of all, thanks so much for all your awesome packages. 

I have a question / possible feature request. Based on my experience so far, it is impossible to determine whether or not you have established a proper connection with google analytics. If the client_id is wrong, I got a nasty:

`code":403,"message":"User does not have sufficient permissions for this profile"
`
Is there some way to test the connection before retrieving data? As is, an error is thrown as soon as the connection fails, causing the whole site to crash. If it's not already possible, I would love a new method like "testConnection" that returns true is a proper connection is established and false if not.

**Comment by freekmurze** [comment]
I'm thinking you could just add a `try/catch` block around the code to determine if the connection is working.
