### ISSUE TITLE
Period.php issue

### ISSUE THREAD

**Issue by ganeshrc35** [spatie/laravel-analytics#239]
I am facing this issue in my server.

It is running in php7.0

(1/1) FatalErrorExceptionsyntax error, unexpected ':', expecting ';' or '{'
--
in Period.php (line 17)

Please help me to fix this.

**Comment by sebastiandedeyne** [comment]
It is something regarding the php version, you're not running php 7 somewhere on your server.

Note that the php version of your CLI can differ from the php version of the web server. Make sure they're *both* on 7.0+
