### ISSUE TITLE
Example - Errors

### ISSUE THREAD

**Issue by curtsheller** [spatie/laravel-analytics#24]
Trying this example from the **ReadMe.md** page after package is installed.
````
/*
* $analyticsData now contains a Collection with 3 columns: "date", "visitors" and "pageViews"
*/
$analyticsData = LaravelAnalytics::getVisitorsAndPageViews(7);
````
error is:

````
ErrorException in TestController.php line 62:
Non-static method Spatie\LaravelAnalytics\LaravelAnalytics::getMostVisitedPages() should not be called statically, assuming $this from incompatible context
````

Double check installed as required. Provider and Aliases set, Credentials checked., artisan published etc...

Then tried
````
$analyticsData = (new LaravelAnalytics)->getMostVisitedPages(365, 20);
````

error as expected is:

````
Argument 1 passed to Spatie\LaravelAnalytics\LaravelAnalytics::__construct() must be an instance of Spatie\LaravelAnalytics\GoogleApiHelper, none given, ...
````

At a lose for figuring out what is wrong and getting this package to work.

Using Laravel 5.1.3 (LTS)

**Comment by freekmurze** [comment]
Are you using the latest version? Have you specified a valid siteId in your config file? It should start with "ga:"

**Comment by curtsheller** [comment]
There is a slid site I'd. Using dev-master.

**Comment by freekmurze** [comment]
I'm not sure what you mean by "slid siteId"

**Comment by curtsheller** [comment]
In my .env file with all my other values that are working.
````
ANALYTICS_SITE_ID=ga:102416808
````

Followed the instructions on getting the credentials from google several times.

The error seems too be suggesting from some searching that the facade is not working. It is trying to call the function as a static method, which it naturally is not.

I'm lost.

Curt

**Comment by lukepolo** [comment]
Shouldn't 
    $analyticsData = (new LaravelAnalytics)->getMostVisitedPages(365, 20);

be 

   LaravelAnalytics::getMostVisitedPages(365, 20);

?

**Comment by curtsheller** [comment]
Either way didn't work as shown in my first message. I tried the second way on a whim and a search trying see if I could resolve the problem.

**Comment by lukepolo** [comment]
Gotcha, just verifying

**Comment by curtsheller** [comment]
I guess there is no resolution or solution for this and I can't use this package. Looked promising. I'll have to look for another solution.

**Comment by sebastiandedeyne** [comment]
If the exception was thrown on `Spatie\LaravelAnalytics\LaravelAnalytics::getMostVisitedPages()`, you're not calling the facade, its not the same as `LaravelAnalytics::getMostVisitedPages()`. I assume the use statement in the controller is incorrect (should be `use LaravelAnalytics;`.

**Comment by curtsheller** [comment]
Thanks for the help. All is working now. It sure isn't easy navigating google.
