### ISSUE TITLE
Force update

### ISSUE THREAD

**Issue by appdezign** [spatie/laravel-analytics#248]
Hi,

I'm using laravel-analytics on the dashboard of my CMS, and because I want the dashboard to load fast, I use cache (lifetime: one day). However, because webmasters do not login every day, they are sometimes still presented with a very slow dashboard after they login (I use five methods of laravel analytics on my dashboard). 

So I tried to find a way to refresh the Analytics data in the background with a task. However, I cannot seem to find a way to force an update of the data. When I run this task, I can set the config value of cache_lifetime_in_minutes to '0' at runtime, and the data is fetched correctly, but it is not written to cache, because ... the lifetime is set to '0'.

So then I tried to manually clear the cache, but the names of the cache are partlty serialized, and I cannot use wildcards when I want to clear cache.

So, that means that I cannot force an update of the cache, right? Or am I missing something?

If my conclusion is correct, then it would be REALLY nice to have a (boolean) $force argument added to the available methods.

**Comment by freekmurze** [comment]
I think the easiest way to solve this is if you roll your own cache and don't use the cache in this package.

```php
$analyticsDate = Cache::rememberForever('yourTagName', function() {
    return ... // fetch data from analytics
});
```

This way you can set the cache name manually.
