### ISSUE TITLE
ReflectionException Class laravel-analytics does not exist

### ISSUE THREAD

**Issue by ignachiou** [spatie/laravel-analytics#254]
I configure the controller as you say in the readme file but hasn't success in the attemp to retrive information.

This is my controller:
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use \Spatie\Analytics\Period;
use Carbon\Carbon;
use Illuminate\Support\Collection;
use \Spatie\Analytics\AnalyticsFacade as Analytics;

class GAController extends Controller{

    public function mediumRetrive(){

        $startDate = new Carbon('2018-03-01');
        $endDate = new Carbon('yesterday');

        $mediumData = Analytics::performQuery(
            Period::create($startDate,$endDate),
            'ga:sessions',
            [
                'metrics' => 'ga:newUsers',
                'dimensions' => 'ga:campaign, ga:sourceMedium, ga:keyword',
            ]

        );
        //console.log($mediumData);

        return view('ga.medium');

    }
}

**Comment by gsabater** [comment]
I'm having the same issue.

I have just installed v3.6 in L5.5
```
use Analytics;
use Spatie\Analytics\Period;
...
public function index()
{
        $analyticsData = Analytics::fetchVisitorsAndPageViews(Period::days(7));
        return $analyticsData;
}
```

And I get `Class laravel-analytics does not exist` meaning that the facade is not returning the correct class.
