### ISSUE TITLE
User does not have any Google Analytics account

### ISSUE THREAD

**Issue by ChristianGerdes** [spatie/laravel-analytics#26]
I get an error when I run
```
$analyticsData = \LaravelAnalytics::getVisitorsAndPageViews(7);
dd($analyticsData);
```
(403) User does not have any Google Analytics account.
I've followed the setup guide, but it just don't work.

In my .env:
ANALYTICS_SITE_ID=...
ANALYTICS_CLIENT_ID=...
ANALYTICS_SERVICE_EMAIL=...

**Comment by freekmurze** [comment]
Make sure you've added the ANALYTICS_SERVICE_EMAIL to the Google Analytics Account otherwise you will get a `403: User does not have any Google Analytics Account`-error.

**Comment by Webcris** [comment]
I receive this error:
User does not have sufficient permissions for this profile.

**Comment by WolfieZero** [comment]
I also have all the correct details including the P12 file being pointed correctly and the service email but still getting the 403 error. The site ID is on the same account that the API was setup on.

**Comment by rampara56** [comment]
I also got the same error.
User does not have sufficient permissions for this profile.
I already added the SERVICE_ACCOUNT_EMAIL, and p12 file as well.

**Comment by CrixuAMG** [comment]
Getting the same issue:
```
{"error":{"errors":[{"domain":"global","reason":"insufficientPermissions","message":"User does not have any Google Analytics account."}],"code":403,"message":"User does not have any Google Analytics account."}}
```

When using the same account details and view Id at the API explorer, I do get a valid response with content back from the API.

I followed the documentation as specified.

**Comment by shimjudavid** [comment]
Getting this error: 
"{"error":{"errors":[{"domain":"global","reason":"required","message":"Login Required","locationType":"header","location":"Authorization"}],"code":401,"message": ▶"
