### ISSUE TITLE
fetch data by passing URL

### ISSUE THREAD

**Issue by vschavala** [spatie/laravel-analytics#260]
Hi,

can i get the page views from analytics by pushing URL
means
can i fetch the data by passing URL to analytics

Ex: "/events "

**Comment by marzoukiniz** [comment]
@vschavala  yes it is possible, you have to loop the $analyticsData and check if $analyticsData[ $i ]['pageTitle']=='events' 

$analyticsData = Analytics::fetchVisitorsAndPageViews( $period );
$size       = count( $analyticsData );
for ( $i = 0; $i < $size; $i ++ ) {
	if ( $analyticsData[ $i ]['pageTitle'] == 'events') {
		$Visitors   $analyticsData[ $i ]['visitors'];
		$PageViews = $analyticsData[ $i ]['pageViews'];
	}
}

**Comment by vschavala** [comment]
Thank you marzoukiniz for your valuable suggestion, but i need passing url, before fetch the data 
 from google analytics

**Comment by marzoukiniz** [comment]
pass it in method parameter and if you do it in view pass it via ajax call. and do the same process
