### ISSUE TITLE
Pagination handling for requests that exceed 10.000 results

### ISSUE THREAD

**Issue by UB3RL33T** [spatie/laravel-analytics#265]
Hello, 

I am querying the GA API over quite large ranges of time, with different metrics and dimensions, exceeding the response of the maximum possible 10.000 results.

I was wondering if there is a handling implemented to retrieve the results that start at the index of +10.001?

**Comment by freekmurze** [comment]
This is currently not implemented. If the code is simple and we'll tested I'd consider accepting a PR.
