### ISSUE TITLE
Infinite Loop fetchTotalVisitorsAndPageViews

### ISSUE THREAD

**Issue by tiriwo** [spatie/laravel-analytics#269]
Why do i get an endless browser loading when i query for example : 

```
Route::get('/analytics/data',function (){
 return response()->json(Analytics::fetchTotalVisitorsAndPageViews(Period::days(2)));
 //return response()->json(Analytics::fetchTopBrowsers(Period::days(1)));

});
``` 
The commented query works fine.  According to GA the website gets roughly 3k users daily, so i don't expect it to cause an infinite loading issue that times out with Maximum execution time of 60 seconds exceeded.

**Comment by stefanocurnis** [comment]
Same issue here. Had to roll back to 3.5.0.

**Comment by laravelcoder** [comment]
also getting the error:

Maximum execution time of 30 seconds exceeded

any fixes for this anyone?

**Comment by freekmurze** [comment]
This is fixed in the latest version.

**Comment by tiriwo** [comment]
Thank You @freekmurze , works like a charm . great package by the way
