### ISSUE TITLE
Google_Exception in Resource.php line 166: (get) missing required param: 'ids'

### ISSUE THREAD

**Issue by acbmv** [spatie/laravel-analytics#27]
Hi !
I have an issue with a laravel fresh install , I have the following error:
Google_Exception in Resource.php line 166: (get) missing required param: 'ids'
If I set my id directly in vendor/spatie/laravel-analytics/src/LaravelAnalytics.php line 298
I have the following error:
Google_Auth_Exception in OAuth2.php line 357: Error refreshing the OAuth2 token, message: '{
"error" : "invalid_grant"
}'
Any thought on why it did'nt work ?

**Comment by jperezr** [comment]
Define in file .env
ANALYTICS_SERVICE_EMAIL=xxxxxx@developer.gserviceaccount.com
ANALYTICS_SITE_ID=ga:xxxxxxx
ANALYTICS_CLIENT_ID=xxxxxxxx.apps.googleusercontent.com

in file config/laravel-analitycs.php

'certificatePath' => storage_path('laravel-analytics/xxxxxxxx.p12'),

**Comment by mrtnbrjs** [comment]
I have the same error, and defining those variables in file .env didn't work, i'm working in a Laravel Homestead Project, if there another solution?

**Comment by freekmurze** [comment]
If you get that error message, you've probably missed a step installating the package or obtaining the right credentials. Do you have a p12 file? Have you got an analytics site id (it should start with "ga:", not UA-")?

**Comment by mrtnbrjs** [comment]
I downloaded the p12 file but the file name start with 'analytics api-xxxxxxxxxxxx.p12', i have to remove the space or how?, and the size of my site id is longer than the example it's 9 characters long, I did the all the steps again and i'm having the same error.

**Comment by rebecca-turner** [comment]
I'm getting the same issue. 

I'm using the correct ID (ga and not UA-) and I have a p12 file.

**Comment by mrtnbrjs** [comment]
I resolve it, you only have to remove in the config/laravel-analytics.php file the "env()", this was causing the invalid grant error. Here an example of how to set the 3 variables:

![screen shot 2015-08-05 at 8 30 58 am](https://cloud.githubusercontent.com/assets/6425108/9088262/56ed66fa-3b4c-11e5-9f6b-6d8393f6bac2.png)

**Comment by rebecca-turner** [comment]
Ah perfect! Thanks!

**Comment by freekmurze** [comment]
Nice!

**Comment by siawashkasra** [comment]
I can't find the the analytics side id, any idea?

**Comment by florgb02** [comment]
Awesome, I was having same issue, Thanks removing the env fixed it.

**Comment by blumtech** [comment]
fixed here too!

**Comment by dheeraj0086** [comment]
i can't find ga:XXXXXXX site id where it is avelabel????
plzzzz help me.....:(

**Comment by mrtnbrjs** [comment]
Try to be more specific, what you can't find? your siteId or the file?

**Comment by dheeraj0086** [comment]
google analytics siteid like:ga:XXXXXXX

try to get data in spatie/laravel-analytics package and in config file required site id

**Comment by dheeraj0086** [comment]
i  concatenat of the namespace ga: with the Analytics view (profile) ID
but its gives me same error:-

(get) missing required param: 'ids';

**Comment by mrtnbrjs** [comment]
I think that you can't find the siteId, in the README.md file Spatie, here there is the info:
https://github.com/spatie/laravel-analytics#how-to-obtain-the-credentials-to-communicate-with-google-analytics
