### ISSUE TITLE
I have this error "User does not have any Google Analytics account"!!!

### ISSUE THREAD

**Issue by webcoweb** [spatie/laravel-analytics#272]
hello 

it shows me this error :

```
Google_Service_Exception (403)
{"error":{"errors":[{"domain":"global","reason":"insufficientPermissions","message":"User does not have any Google Analytics account."}],"code":403,"message":"User does not have any Google Analytics account."}}
```

may you help me to solve it?

thanks.

**Comment by brendt** [comment]
The README explains how to setup Google credentials to use this package: https://github.com/spatie/laravel-analytics#how-to-obtain-the-credentials-to-communicate-with-google-analytics
