### ISSUE TITLE
Missing Tracking code

### ISSUE THREAD

**Issue by cromartie1984** [spatie/laravel-analytics#277]
I got this error : 
**Missing Tracking Code error
Page https:/**** for property **** is missing valid tracking code.
No Hits : Property **** is not receiving hits.**

The tracking code is in the json file and the view id you pass in config/analytics.php ?

You must add Global site tag in head too?

**Comment by zymawy** [comment]
You Need To Add This Code To The Pages You Want To Track
```js
<script async src="https://www.googletagmanager.com/gtag/js?id=YOURIDHERE"></script>
<script>
    window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '');

</script>
<script>
  !function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on"];analytics.factory=function(t){return function(){var e=Array.prototype.slice.call(arguments);e.unshift(t);analytics.push(e);return analytics}};for(var t=0;t<analytics.methods.length;t++){var e=analytics.methods[t];analytics[e]=analytics.factory(e)}analytics.load=function(t,e){var n=document.createElement("script");n.type="text/javascript";n.async=!0;n.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var o=document.getElementsByTagName("script")[0];o.parentNode.insertBefore(n,o);analytics._loadOptions=e};analytics.SNIPPET_VERSION="4.1.0";
  analytics.load("");
  analytics.page();
  }}();
</script>

**Comment by cromartie1984** [comment]
that's what i need after a while. But i remember i did not need this code before weird.

**Comment by paradisetechsoftsolutions** [comment]
getting this error

`{"error":{"errors":[{"domain":"global","reason":"insufficientPermissions","message":"User does not have any Google Analytics account."}],"code":403,"message":"User does not have any Google Analytics account."}}`

but i already gives permissions

**Comment by freekmurze** [comment]
@paradisetechsoftsolutions If you are getting that error, you misconfigured something. Retrace your steps on follow the instructions on the readme. If you think they contain an error, please submit a PR.
