### ISSUE TITLE
must provide a valid view id  in production 

### ISSUE THREAD

**Issue by zymawy** [spatie/laravel-analytics#278]
Hello, I have an issue with my production server. Everything seems to work properly. 
But when I upload to the server now it's asking for a view id

exception:
`"Spatie\Analytics\Exceptions\InvalidConfiguration"`

message 
`There was no view id specified. You must provide a valid view id to execute querys on Google Analytics.`

any suggestion?

**Comment by freekmurze** [comment]
Take a look at the readme on how to install this package.

If you’ve changes the config, don’t forget to clear the config cache.
