### ISSUE TITLE
Laravel 4 Support?

### ISSUE THREAD

**Issue by hamstu** [spatie/laravel-analytics#28]
I'm not too familiar package dev, what would it take to make this compatible with L4.2?

(Fwiw, I haven't tried it, but it looks to me like it does depend on some newer L5 stuff, if I'm reading the composer.json right.)

**Comment by sebastiandedeyne** [comment]
Writing a laravel 5 compatible service provider *might* be enough, but don't take my word on it, there could be some small incompatibilities.

Alternatively you could check out our framework-agnostic package (https://github.com/spatie/analytics-statistics). We're not actively updating it but it has feature parity with this one for now.

**Comment by hamstu** [comment]
@sebastiandedeyne Cool, thanks!  I might take a stab at it when I come to working on this later. I'll let you know :+1:

**Comment by YOzaz** [comment]
:+1: to this one. Laravel 4 is not dead yet!
