### ISSUE TITLE
Import facade

### ISSUE THREAD

**Issue by HansDrijver** [spatie/laravel-analytics#284]
I know this issue was also talked about in #168 and #204, but it still exists for me.

When i put:

```php
use Spatie\Analytics\Analytics;
```

It gives the error 'Non-static method should not be called statically'

But when I only put:

```php
use Analytics;
```

I gives a white page on refresh or says "The use statement with non-compound name 'Analytics' has no effect " when starting.

I am using Laravel 5.7.5 and although it says the facade should be automatically setup, it wasn't working so I also added this manually to the // config/app.php:

```php
'Analytics' => Spatie\Analytics\AnalyticsFacade::class,
```

But it still is not working.

What could be wrong?

Thank you in advance!

**Comment by freekmurze** [comment]
Probably you have cached your configuration. Try running `php artisan config:clear`.

**Comment by alishaown** [comment]
Hi,
Unfortunately, the php artisan config:clear did not work for me. Any other solution for this same issue?

**Comment by reubenwedson** [comment]
use  Spatie\Analytics\AnalyticsFacade as Analytics

**Comment by reubenwedson** [comment]
> Hi,
> Unfortunately, the php artisan config:clear did not work for me. Any other solution for this same issue?

use Spatie\Analytics\AnalyticsFacade as Analytics
