### ISSUE TITLE
null site id

### ISSUE THREAD

**Issue by fatenfalfoul** [spatie/laravel-analytics#285]
Hi I mùust use laravel-analytics 1.4 (server php 5.5 requirement)

I have 
Google_Exception in Resource.php line 169:
(get) missing required param: 'ids'

caused by null siteId (viewed when running config('laravel-analytics') from a tinker console

Help please

**Comment by freekmurze** [comment]
We don't support v1 anymore.

**Comment by fatenfalfoul** [comment]
THANKS
