### ISSUE TITLE
Can't get analytics to work

### ISSUE THREAD

**Issue by fabiomiguelmfernandes** [spatie/laravel-analytics#287]
Hello guys,

i'm having a problem with this package.

If i put a google analytics Tracking Code on my website, i get the results and live users but, when i use this package i cannot get that data.

Using laravel 5.7 on localhost, did the Installation correctlly

Any help?

**Comment by freekmurze** [comment]
There's too little info here for us to help you. Take a look at these instructions: https://github.com/spatie/laravel-analytics#how-to-obtain-the-credentials-to-communicate-with-google-analytics

If you need help using the package you can also use a public forum such as laravel.io or the laracasts forum.

**Comment by richardfeliciano** [comment]
Google updated analytics UI, and now this instructions wont match the UI.
