### ISSUE TITLE
Installation Problem - L5.1

### ISSUE THREAD

**Issue by thiduzz** [spatie/laravel-analytics#29]
It seems that the installation has a typo or something like this, i am trying to run the composer require of this package and well, that's the result:

vagrant@homestead:~/Sites/vizad-boot$ composer require spatie/laravel-analytics
Using version dev-master for spatie/laravel-analytics ./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for spatie/laravel-analytics dev-master -> satisfiable by spatie/laravel-analytics[dev-master].
    - spatie/laravel-analytics dev-master requires google/apiclient 1.1.* -> no matching package found.
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
Installation failed, reverting ./composer.json to its original content.

**Comment by freekmurze** [comment]
You should require the package with:
```bash
composer require spatie/laravel-analytics
```
This will pull in v1.2.1.

**Comment by thiduzz** [comment]
I am sorry, but if you take a look closer i actually used the same line in the beginning.

**Comment by freekmurze** [comment]
Are you doing this in a fresh laravel 5.1 installation?
