### ISSUE TITLE
Could not find a credentials file at `/home/legendary/Laravel_class/project2/storage/app/analytics/service-account-credentials.json`.

### ISSUE THREAD

**Issue by Legendary-Tony** [spatie/laravel-analytics#292]
How can I solve this pls....

**Comment by freekmurze** [comment]
Make sure you create a json credentials file and specify the right path to it in the config file of this package.

More info https://github.com/spatie/laravel-analytics#how-to-obtain-the-credentials-to-communicate-with-google-analytics
