### ISSUE TITLE
Argument 1 passed to Spatie\Analytics\Analytics::fetchTotalVisitorsAndPageViews() must be an instance of Spatie\Analytics\Period, instance of Carbon\Carbon given, called in /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 223

### ISSUE THREAD

**Issue by gjqholdings** [spatie/laravel-analytics#294]
My controller: 
use Analytics;
use Spatie\Analytics\Period;
use Carbon\Carbon; 

public function index(){
      $analyticsData = Analytics::fetchTotalVisitorsAndPageViews(Period::days(7));
      $last_weeks_vists = Analytics::fetchTotalVisitorsAndPageViews(Carbon::now()->subDays(7)->startOfWeek(), Carbon::now()->subDays(7)->endOfWeek(), $groupBy = 'date')->lists('visitors');
      $this_weeks_vists = Analytics::fetchTotalVisitorsAndPageViews(Carbon::now()->startOfWeek(), Carbon::now()->endOfWeek(), $groupBy = 'date')->lists('visitors');
      $sidebar = $this->allUserSidebar();
      $mainContent = $this->allUserDashboard()->with(['analyticsData' => $analyticsData], ['this_weeks_vists' => $this_weeks_vists], ['last_weeks_vists' => $last_weeks_vists]);
      return view('_layouts.userMaster', compact('mainContent', 'sidebar', 'analyticsData'));
    }

My Period.php:

<?php

namespace Spatie\Analytics;

use DateTime;
use Carbon\Carbon;
use Analytics;
use Spatie\Analytics\Exceptions\InvalidPeriod;

class Period
{
    /** @var \DateTime */
    public $startDate;

    /** @var \DateTime */
    public $endDate;

    public static function create(DateTime $startDate, $endDate): self
    {
        return new static($startDate, $endDate);
    }

    public static function days(int $numberOfDays): self
    {
        $endDate = Carbon::today();

        $startDate = Carbon::today()->subDays($numberOfDays)->startOfDay();

        return new static($startDate, $endDate);
    }

    public static function months(int $numberOfMonths): self
    {
        $endDate = Carbon::today();

        $startDate = Carbon::today()->subMonths($numberOfMonths)->startOfDay();

        return new static($startDate, $endDate);
    }

    public static function years(int $numberOfYears): self
    {
        $endDate = Carbon::today();

        $startDate = Carbon::today()->subYears($numberOfYears)->startOfDay();

        return new static($startDate, $endDate);
    }

    public function __construct(DateTime $startDate, DateTime $endDate)
    {
        if ($startDate > $endDate) {
            throw InvalidPeriod::startDateCannotBeAfterEndDate($startDate, $endDate);
        }

        $this->startDate = $startDate;

        $this->endDate = $endDate;
    }
}

My analytics.php

<?php

namespace Spatie\Analytics;

use Carbon\Carbon;
use Spatie\Analytics\Period;
use Google_Service_Analytics;
use Illuminate\Support\Collection;
use Illuminate\Support\Traits\Macroable;

class Analytics
{
    use Macroable;

    /** @var \Spatie\Analytics\AnalyticsClient */
    protected $client;

    /** @var string */
    protected $viewId;

    /**
     * @param \Spatie\Analytics\AnalyticsClient $client
     * @param string                            $viewId
     */
    public function __construct(AnalyticsClient $client, string $viewId)
    {
        $this->client = $client;

        $this->viewId = $viewId;
    }

    /**
     * @param string $viewId
     *
     * @return $this
     */
    public function setViewId(string $viewId)
    {
        $this->viewId = $viewId;

        return $this;
    }

    public function fetchVisitorsAndPageViews(Period $period): Collection
    {
        $response = $this->performQuery(
            $period,
            'ga:users,ga:pageviews',
            ['dimensions' => 'ga:date,ga:pageTitle']
        );

        return collect($response['rows'] ?? [])->map(function (array $dateRow) {
            return [
                'date' => Carbon::createFromFormat('Ymd', $dateRow[0]),
                'pageTitle' => $dateRow[1],
                'visitors' => (int) $dateRow[2],
                'pageViews' => (int) $dateRow[3],
            ];
        });
    }

    public function fetchTotalVisitorsAndPageViews(Period $period): Collection
    {
        $response = $this->performQuery(
            $period,
            'ga:users,ga:pageviews',
            ['dimensions' => 'ga:date']
        );

        return collect($response['rows'] ?? [])->map(function (array $dateRow) {
            return [
                'date' => Carbon::createFromFormat('Ymd', $dateRow[0]),
                'visitors' => (int) $dateRow[1],
                'pageViews' => (int) $dateRow[2],
            ];
        });
    }

    public function fetchMostVisitedPages(Period $period, int $maxResults = 20): Collection
    {
        $response = $this->performQuery(
            $period,
            'ga:pageviews',
            [
                'dimensions' => 'ga:pagePath,ga:pageTitle',
                'sort' => '-ga:pageviews',
                'max-results' => $maxResults,
            ]
        );

        return collect($response['rows'] ?? [])
            ->map(function (array $pageRow) {
                return [
                    'url' => $pageRow[0],
                    'pageTitle' => $pageRow[1],
                    'pageViews' => (int) $pageRow[2],
                ];
            });
    }

    public function fetchTopReferrers(Period $period, int $maxResults = 20): Collection
    {
        $response = $this->performQuery($period,
            'ga:pageviews',
            [
                'dimensions' => 'ga:fullReferrer',
                'sort' => '-ga:pageviews',
                'max-results' => $maxResults,
            ]
        );

        return collect($response['rows'] ?? [])->map(function (array $pageRow) {
            return [
                'url' => $pageRow[0],
                'pageViews' => (int) $pageRow[1],
            ];
        });
    }

    public function fetchUserTypes(Period $period): Collection
    {
        $response = $this->performQuery(
            $period,
            'ga:sessions',
            [
                'dimensions' => 'ga:userType',
            ]
        );

        return collect($response->rows ?? [])->map(function (array $userRow) {
            return [
                'type' => $userRow[0],
                'sessions' => (int) $userRow[1],
            ];
        });
    }

    public function fetchTopBrowsers(Period $period, int $maxResults = 10): Collection
    {
        $response = $this->performQuery(
            $period,
            'ga:sessions',
            [
                'dimensions' => 'ga:browser',
                'sort' => '-ga:sessions',
            ]
        );

        $topBrowsers = collect($response['rows'] ?? [])->map(function (array $browserRow) {
            return [
                'browser' => $browserRow[0],
                'sessions' => (int) $browserRow[1],
            ];
        });

        if ($topBrowsers->count() <= $maxResults) {
            return $topBrowsers;
        }

        return $this->summarizeTopBrowsers($topBrowsers, $maxResults);
    }

    protected function summarizeTopBrowsers(Collection $topBrowsers, int $maxResults): Collection
    {
        return $topBrowsers
            ->take($maxResults - 1)
            ->push([
                'browser' => 'Others',
                'sessions' => $topBrowsers->splice($maxResults - 1)->sum('sessions'),
            ]);
    }

    /**
     * Call the query method on the authenticated client.
     *
     * @param Period $period
     * @param string $metrics
     * @param array  $others
     *
     * @return array|null
     */
    public function performQuery(Period $period, string $metrics, array $others = [])
    {
        return $this->client->performQuery(
            $this->viewId,
            $period->startDate,
            $period->endDate,
            $metrics,
            $others
        );
    }

    /*
     * Get the underlying Google_Service_Analytics object. You can use this
     * to basically call anything on the Google Analytics API.
     */
    public function getAnalyticsService(): Google_Service_Analytics
    {
        return $this->client->getAnalyticsService();
    }
}

My carbon file is too big so i wont paste it in here.

IS is my full error:
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Argument 1 passed to Spatie\Analytics\Analytics::fetchTotalVisitorsAndPageViews() must be an instance of Spatie\Analytics\Period, instance of Carbon\Carbon given, called in /home/vagrant/sites/gjqholdings/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 223

i went all over internet and it seems to be I'm the first one with this issue.

**Comment by freekmurze** [comment]
Make sure you read this section in the readme on how to use our package: https://github.com/spatie/laravel-analytics#usage

**Comment by freekmurze** [comment]
`public function fetchTotalVisitorsAndPageViews(Period $period): Collection`

You should create a `Period` object and pass that to `fetchTotalVisitorsAndPageViews`.

**Comment by gjqholdings** [comment]
> `public function fetchTotalVisitorsAndPageViews(Period $period): Collection`
> 
> You should create a `Period` object and pass that to `fetchTotalVisitorsAndPageViews`.

I have Made created objects in the Period.
If this is what you meant, then it didnt help me either :((

**Period.php:**
public static function weeks(int $numberOfWeeks): self
    {
        $startDate = Carbon::now()->subDays(7)->startOfWeek();
        $endDate = Carbon::now();
        $startDate = Carbon::now()->startOfWeek();
        $endDate = Carbon::now()->endOfWeek();
        $endDate = Carbon::today();
        $startDate = Carbon::today()->subDays($numberOfWeeks)->startOfWeek();

        return new static($startDate, $endDate);
    }


I think i miss understand something what you have said. Can you please explain it to me more open plz?
