### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by aminalali8** [spatie/laravel-analytics#300]
while trying to install this package on a Laravel 5.7 I got the following from composer 
 Problem 1
    - Can only install one of: laravel/framework[v5.7.28, 5.8.x-dev].
    - Can only install one of: laravel/framework[5.8.x-dev, v5.7.28].
    - Can only install one of: laravel/framework[5.8.x-dev, v5.7.28].
    - spatie/laravel-analytics 3.7.0 requires laravel/framework ~5.8.0 -> satisfiable by laravel/framework[5.8.x-dev].
    - Installation request for spatie/laravel-analytics ^3.7 -> satisfiable by spatie/laravel-analytics[3.7.0].
    - Installation request for laravel/framework (locked at v5.7.28, required as 5.7.*) -> satisfiable by laravel/framework[v5.7.28].

**Comment by freekmurze** [comment]
v3.6.3 has support for Laravel 5.7

https://github.com/spatie/laravel-analytics/blob/3.6.3/composer.json#L25
