### ISSUE TITLE
unable to install 3.6.3 because of nestbot/carbon version

### ISSUE THREAD

**Issue by lorvent** [spatie/laravel-analytics#301]
Hello,

because of carbon version in dependency
https://github.com/spatie/laravel-analytics/blob/3.6.3/composer.json#L27

not able to install it,

laravel 5.8 requires `^1.26.3` https://github.com/laravel/framework/blob/5.8/composer.json#L28

so can you please adjust version accordingly?

Also...pls bump version to something like 3.6.4, because of our requirements, we still need to support php 7.1 

thanks

**Comment by lorvent** [comment]
can this get any love/attention @freekmurze

**Comment by rubenvanassche** [comment]
Hi @lorvent 

I just installed Laravel 5.8 clean with spatie/laravel-analytics:3.6.3 and everything is working fine. Can you please check your composer.json again if there is another package causing the problem?

**Comment by lorvent** [comment]
thats because you made a new commit
https://github.com/spatie/laravel-analytics/commit/f8eea417d0172d2a1ee60df38bb70a7cadb4c9a9

it is installing 3.6.x-dev instead of 3.6.3

end of the day, it is working for me and thank you so much for making it work 💃

**Comment by willsilvano** [comment]
I have the same issue.
I'm need to install this package in PHP 7.1.13 :/

**Comment by willsilvano** [comment]
`composer require spatie/laravel-analytics:"3.6.*"` solved my problem.
