### ISSUE TITLE
How can i utilize this packages with Laravel 5.7?

### ISSUE THREAD

**Issue by asimshazad** [spatie/laravel-analytics#307]
Is there any way to install it with L5.7,as for some reasons i can't update my version to 5.8

Thank you.

**Comment by brendt** [comment]
Unfortunately we don't support older Laravel versions. It's our way of helping the community stay up to date. 

Updating is something that you should definitely consider doing: holding off on update only makes matters worse in the long run, or results in a full-blown legacy project very quickly.
