### ISSUE TITLE
is there is a way to set the period to application life time ?

### ISSUE THREAD

**Issue by faniabdo99** [spatie/laravel-analytics#308]
Hi , i would like to get some statics like the browsers usage not just for the last week or month , is there is a way to set the period to application life time or something like that ? thanks !

**Comment by Reflow1319** [comment]
You can do something like the following

just change '01/01/2015' to the start date of your app
```
$startDate = Carbon::createFromFormat('d/m/Y', '01/01/2015'));
    $endDate = Carbon::now();
    $period = Period::create($startDate, $endDate);
    Analytics::fetchTopBrowsers($period)
```

**Comment by mrpritchett** [comment]
You could also go back to the start date of all Google Analytics data, which is 2005-01-01
