### ISSUE TITLE
Class 'LaravelAnalytics' Not found

### ISSUE THREAD

**Issue by Phorce** [spatie/laravel-analytics#31]
On my local machine, it works fine. 

When I upload to the server, I'm getting the error: "Class 'LaravelAnalytics' not found" 

I have ran php composer.phar update but still I am getting this error.

Any ideas why?

**Comment by Phorce** [comment]
Issued solved by: 

php artisan cache:clear 

And

php artisan config:clear

**Comment by sebastiandedeyne** [comment]
Good to see it's resolved :)
