### ISSUE TITLE
code":401,"message":"Login Required"

### ISSUE THREAD

**Issue by kdInfo13** [spatie/laravel-analytics#310]
{"error":{"errors":[{"domain":"global","reason":"required","message":"Login Required","locationType":"header","location":"Authorization"}],"code":401,"message":"Login Required"}}

am getting this error when call Analytics::fetchVisitorsAndPageViews

**Comment by atymic** [comment]
Did you follow the exact instructions in the readme?
It's possible you might have missed a step (hence the auth error)
