### ISSUE TITLE
view id

### ISSUE THREAD

**Issue by mortezapiri** [spatie/laravel-analytics#313]
error There was no view id specified. You must provide a valid view id to execute querys on Google Analytics.
i run command
`php artisan view:clear`
and 
`php artisan config:clear`

and i chack view id on google analytics and Equal to analytics.php in line 8 
` 'view_id' => env('183352943'),`

**Comment by andrewnclark** [comment]
It sounds like you have mis-configured the package. You either need to add the ID directly into the config file like so:

```
/*
* The view id of which you want to display data.
*/
'view_id' => '183352943',
```

Or alternatively (and largely preferred) you add the following line to your `.env` file and make no changes at all to the provided config file.

`ANALYTICS_VIEW_ID=183352943`
