### ISSUE TITLE
Nothing to publish for tag [charts_assets]

### ISSUE THREAD

**Issue by DorsafDrBs** [spatie/laravel-analytics#315]
i instaled  composer require consoletvs/charts and i add ConsoleTVs\Charts\ChartsServiceProvider::class,   and 'charts'=>ConsoleTVs\Charts\Charts::class,
also i ran php artisan vendor:publish --tag=charts_config
  but when i  run  php artisan vendor:publish --tag=charts_assets --force , i get Nothing to publish for tag [charts_assets]
Laravel framework version 5.3.31
PHP version 7.1.3

how can i solve it ?

**Comment by AlexVanderbist** [comment]
Wrong repo, good luck tho!
