### ISSUE TITLE
Wrong class names and static errors

### ISSUE THREAD

**Issue by passika** [spatie/laravel-analytics#316]
'provider' => [
    ...
    'Spatie\Analytics\LaravelAnalyticsServiceProvider',
    ...
];
should be 
Spatie\Analytics\AnalyticsServiceProvider::class,

'aliases' => [
    ...
    'LaravelAnalytics' => 'Spatie\Analytics\LaravelAnalyticsFacade',
    ...
];
'LaravelAnalytics' => Spatie\Analytics\AnalyticsFacade::class,

but after this fix still error
Non-static method Spatie\Analytics\Analytics::getAnalyticsService() should not be called statically

**Comment by freekmurze** [comment]
Please add this where you're using our package

```
use Analytics;
```
