### ISSUE TITLE
Code sample for Real Time Visitors

### ISSUE THREAD

**Issue by alicinci** [spatie/laravel-analytics#317]
I wanted to share a working code with you about Real Time Visitors.

In controller:

    public function dashboard()
    {
       $activeVisitors = json_encode($this->activeVisitors());

       return view('dashboard', compact('activeVisitors'));
    }

    public function activeVisitors()
    {
       $active = Analytics::getAnalyticsService();

       return $active->data_realtime->get(
    		'ga:'.config('analytics.view_id'),
    		'rt:activeUsers'
    	);
    }

In blade:

      @php
         $jsonActive = json_decode($activeVisitors, true);
      @endphp

       {{ $jsonActive['totalsForAllResults']['rt:activeUsers'] }}

**Comment by Oxicode** [comment]
You are good man
