### ISSUE TITLE
cURL error 77: error setting certificate verify locations:

### ISSUE THREAD

**Issue by NeonExzelcis** [spatie/laravel-analytics#318]
I don't know why i get this error after i follow all instructions

![image](https://user-images.githubusercontent.com/51989901/61340668-e2218b80-a875-11e9-8b14-bf7cf8f00a6c.png)

I also configure my php.ini in xampp but still i get this error. Please help me.

this is required part of my composer.json

![image](https://user-images.githubusercontent.com/51989901/61340907-ee5a1880-a876-11e9-8879-4edd098098b0.png)

**Comment by freekmurze** [comment]
This error is not related to this package.
