### ISSUE TITLE
Laravel Analytics have support query search console ?

### ISSUE THREAD

**Issue by thinha** [spatie/laravel-analytics#319]

**Comment by atymic** [comment]
Can you expand your question to make it more clear what you are asking please?

**Comment by thinha** [comment]
I have accessed search console data (webmaster tool) in google analytics, so i query into data search console ?

**Comment by AlexVanderbist** [comment]
Nope, it's limited to the methods described in the readme. Feel free to open a PR to add anything you might want to see in this package (as long as it uses the same Google Analytics API)
