### ISSUE TITLE
in Macroable.php line 74: Method integre does not exist laravel 5.5

### ISSUE THREAD

**Issue by NoorAbdulAziz** [spatie/laravel-analytics#321]
i am using laravel 5.5
when i execute migrate, i got the following error.
 in Macroable.php line 74: Method integre does not exist
need your help.
what it caused by? and how can i fix it?

**Comment by freekmurze** [comment]
Can you post the full stack trace and exact error message?

**Comment by NoorAbdulAziz** [comment]
![migrate](https://user-images.githubusercontent.com/53452827/62100626-b2985900-b24f-11e9-9b48-24e5ee3b492e.PNG)

**Comment by freekmurze** [comment]
`integre` is not a function from this package. Where are you calling a function with this name in your app?

**Comment by NoorAbdulAziz** [comment]
> `integre` is not a function from this package. Where are you calling a function with this name in your app?

Sir i am not calling this function this was generated automatically.

**Comment by freekmurze** [comment]
`integre` is not a function in this package. So I'm thinking somewhere in your app or other dependencies the non-existing function is called.

**Comment by khaledmostafaismaiel** [comment]
i have same problem in Laravel Framework 5.4.36 
and i don't know what to do yet.

**Comment by PedroWC** [comment]
The method name integre() is wrong. Go to database/migrations and the file you used to configure the table and change it to integer()
