### ISSUE TITLE
includeEmptyRows

### ISSUE THREAD

**Issue by golchha21** [spatie/laravel-analytics#322]
Upon performing the quires I am missing out from dates from the range specified.
In the Google Analytics Panel I see that the values on certain dates are zero(0). To get those values I need to set **includeEmptyRows** as true.

How can I do so?

P.S.:
Reference for the [**includeEmptyRows**](https://developers.google.com/analytics/devguides/reporting/core/v4/rest/v4/reports/batchGet#ReportRequest.FIELDS.include_empty_rows)

**Comment by AlexVanderbist** [comment]
We currently do not support this. Feel free to send a PR that adds this as a boolean parameter.

Alternatively, to fix your issue yourself you could manually merge the resulting data with an array with all days set to 0. Good luck!
