### ISSUE TITLE
Laravel 6.0 support

### ISSUE THREAD

**Issue by hassanazimi** [spatie/laravel-analytics#324]
Any chance you can update this to be compatible with Laravel 6, please?

**Comment by AlexVanderbist** [comment]
We're currently waiting for an external package to be tagged - should be soon. We'll use #323 for further discussion.

**Comment by Nisthar** [comment]
@AlexVanderbist does it support laravel 6.0 yet?

**Comment by freekmurze** [comment]
Yes
