### ISSUE TITLE
Can I get Demographics data for dynamic url? 

### ISSUE THREAD

**Issue by MohamedAhmed12** [spatie/laravel-analytics#329]
How could I get Demographics Data and interests of the visitors for my users profiles pages like:
www.adSoldiers.com/${user-profile}

so I want to get age, gender and interest of each visitor for each specific user on my site, is this even possible with google analytics

**Comment by freekmurze** [comment]
The package doesn't provide that data out of the box. You'll have to research and write such a call yourself.

https://github.com/spatie/laravel-analytics#all-other-google-analytics-queries

**Comment by MohamedAhmed12** [comment]
I've done that using 
public function performQuery(Period $period, string $metrics, array $others = [])
and using ('filter' => ga:pagePath=@/pagePath) it works with the pageviews metric but didn't work with  (age, gender, interest) dimensions.
