### ISSUE TITLE
Can I get Dymographics from dynamic sub path ?

### ISSUE THREAD

**Issue by MohamedAhmed12** [spatie/laravel-analytics#330]
How could I get Demographics Data and interests of the visitors for my users profiles from sub path pages like:
www.adSoldiers.com/${user-profile}

so I want to get age, gender and interest of each visitor for each specific user on my site, is this even possible with google analytics

I've done that using
public function performQuery(Period $period, string $metrics, array $others = [])

and using ('filter' => ga:pagePath=@/pagePath) it works with (ga:pageviews metric and ga:pagePath dimension ) as so:
	['dimensions' => 'ga:pagePath', "filters" => "ga:pagePath=@/test.php"]

but didn't work with (age, gender, interest) dimensions:
        ["dimensions" => "ga:userGender", "filters" => "ga:pagePath=@/test.php"]

**Comment by AlexVanderbist** [comment]
Hi, I'm afraid my knowledge of Google Analytics isn't good enough to help you with this issue. Seems to be more an analytics issue anyways, I'd suggest asking again on Stackoverflow or Google forum's. Good luck!
