### ISSUE TITLE
Argument 1 passed to Google_Client::setCache() must be an instance of Google\Auth\CacheInterface

### ISSUE THREAD

**Issue by MiqueiasMaia** [spatie/laravel-analytics#339]
I'm getting the following error message when I try to use `$pages = Analytics::fetchMostVisitedPages(Period::days(1));`

> Symfony\Component\Debug\Exception\FatalThrowableError
> Argument 1 passed to Google_Client::setCache() must be an instance of Google\Auth\CacheInterface, instance of Symfony\Component\Cache\Adapter\Psr16Adapter given, called in C:\...\vendor\spatie\laravel-analytics\src\AnalyticsClientFactory.php on line 45

**Comment by AlexVanderbist** [comment]
Hey, if you run `composer update` it should pull in a newer version of either the package or `google/apiclient` that should fix the issue. If it doesn't, feel free to open a new issue :) 

Good luck!
