### ISSUE TITLE
ErrorException Non-static method Spatie\Analytics\Analytics::fetchVisitorsAndPageViews() should not be called statically

### ISSUE THREAD

**Issue by Dilshan97** [spatie/laravel-analytics#340]
I try this package. but it doesn't work. please help me to fix this issue. the error is like this.

`ErrorException Non-static method Spatie\Analytics\Analytics::fetchVisitorsAndPageViews() should not be called statically`

`<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Spatie\Analytics\Analytics;
use Spatie\Analytics\Period;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $analyticsData = Analytics::fetchVisitorsAndPageViews(Period::days(7));

        dd($analyticsData);
        
    }
}`

**Comment by freekmurze** [comment]
You probably didn't import the namespace.

Add `Use Analytics` at the top of your file.

**Comment by Dilshan97** [comment]
I already add `Use Analytics ` but it doesn't work

**Comment by reubenwedson** [comment]
> I already add `Use Analytics ` but it doesn't work

import this to your class

`use Spatie\Analytics\AnalyticsFacade as Analytics;`
