### ISSUE TITLE
How to retrieve info from a specific page

### ISSUE THREAD

**Issue by lucasvrm** [spatie/laravel-analytics#35]
Hello!

Is there any way to retrieve info from a specific page?

I have a lot of pages like 
http://aaaaaa.com/KldaFg
http://aaaaaa.com/JueZC
http://aaaaaa.com/kLLem
etc

and I want to retrieve data from only one of them...

How can I accomplish that?

**Comment by freekmurze** [comment]
Hi,

the package doesn't provide a specific method do to that, but you can perform [your own custom query](https://github.com/spatie/laravel-analytics#all-other-google-analytics-queries). I'm preetysure what you're trying to do is possible. Try to find the answer in the [core reporting API](https://developers.google.com/analytics/devguides/reporting/core/v3/)
