### ISSUE TITLE
caching realtime query

### ISSUE THREAD

**Issue by triadsk** [spatie/laravel-analytics#36]
Hi

realtime query caching is not working, like it should. Debugging your package I figured out, that in:

*GoogleApiHelper->performRealTimeQuery()*

method, when I change
```
        if ($this->useRealTimeCache()) {
            $this->cache->put($realTimeCacheName, $googleAnswer, Carbon::now()->addSeconds($this->realTimeCacheLifeTimeInSeconds));
        }
```
to
```
        if ($this->useRealTimeCache()) {
            $this->cache->put($realTimeCacheName, $googleAnswer, $this->realTimeCacheLifeTimeInSeconds*60);
        }
```
it starts to work. But when using that Carbon style it's not working. I've checked tha Cache contract of in Laravel and I think you're right, they provide an option to pass DateTime instance (which Carbon is of course) but simply it does not work.

Do you have any idea why? Could you - as a workaround - change the code to proposed version without that Carbon instance?

**Comment by triadsk** [comment]
Whoaaa, I was blind. The problem is totally elsewhere :) The cache contract expects "minutes", it cannot work in seconds. In other words it will work only if the realTimeCacheLifeTimeInSeconds >= 60. We are passing correct Carbon instance, where we can set 30 seconds cache, but Laravel will floor that to a nearest minute - which in my case is zero. That's why it's not working. So actually Laravel constraints are causing your package cannot use seconds but minutes. All testes and confirmed. 

Issue was already reported, but I think it's not working again (or still): https://github.com/laravel/framework/issues/2954

https://laracasts.com/discuss/channels/general-discussion/caching-less-than-1-minute
http://laravel.io/forum/04-10-2014-caching-under-1-second

**Comment by freekmurze** [comment]
Ok, I'm glad you quickly found the root of the problem.

One way you could make it work is to cache for more that a minute and manually clearing the cache when you detect cache is x seconds old.
