### ISSUE TITLE
laravel-analytics is showing empty data

### ISSUE THREAD

**Issue by Siwarr** [spatie/laravel-analytics#362]
hello,
i was working with laravel-analytics using spaties and i installed this package and did exactly what i found in this project, but every time i die dump any Analytics data it always shows null as a result.
what is the cause of this  errror please ?
Edit : i use laravel 6

**Comment by erskull** [comment]
$response = $this->performQuery(
            $period,
            'ga:users ,ga:pageviews',
            ['dimensions' => 'ga:date,ga:pageTitle']
        );

**Comment by erskull** [comment]
In you analytics.php on vendor if you pro
$response = $this->performQuery(
            $period,
            'ga:users ,ga:pageviews',
            ['dimensions' => 'ga:date,ga:pageTitle']
        );

if you new, in your controller insert this
$response = Analytics::performQuery (Period::days(2),
                                'ga:users ,ga:pageviews',
                                [
                                    'dimensions' => 'ga:date,ga:pageTitle',
                                ]
                            );
                            // dd($response['rows']);
            return collect($response['rows'] ?? [])->map(function (array $dateRow) {
                return [
                    'date' => Carbon::createFromFormat('Ymd', $dateRow[0]),
                    'pageTitle' => $dateRow[1],
                    'visitors' => (int) $dateRow[2],
                    'pageViews' => (int) $dateRow[3],
                ];
            });

**Comment by Pratik400** [comment]
wow thank you. just what i needed. may god bless you

**Comment by erskull** [comment]
Thank you @Pratik400. Hope you had a good day. This was actually discovered by a friend @oerajju
