### ISSUE TITLE
For Multi-tenant App Config View_ID Customize

### ISSUE THREAD

**Issue by lovecoding-git** [spatie/laravel-analytics#368]
Hi @freekmurze 

Thank you for such great package.
May I ask one thing?

I am going to use this package for multi-tenant app.
Means analytics `VIEW_ID` will be different per tenant and `json` file as well.

My concern is here,

I will need to override config `view_id` in `AppServiceProvider`.

Let's say I save `view_id` in database then whenever app is running, that query will be run every time? right?

My opinion:

-Is there any way to override `view_id` and `json` file path only when this package is used to show analytics?
In my case, I will call it in only dashboard page.

So before I call functions in your package, if I can override config variables that would be great!
Is this possible for now? 
Or is there any better solution?

Thank you.

**Comment by lovecoding-git** [comment]
Okay, I figured out.

**Comment by arkaitzgarro** [comment]
@lovecoding-git could you please share how did you manage to solve this problem?

**Comment by lovecoding-git** [comment]
@arkaitzgarro 
Well, just override config value just before you call analytics.
