### ISSUE TITLE
Missing Client Id from Developer Console

### ISSUE THREAD

**Issue by WolfieZero** [spatie/laravel-analytics#37]
Not sure if I've missed something or Google has changed things dramatically but I created a service account and got my p12 cert. Now on the credentials screen I see the email address (`xx-xxx@developer.gserviceaccount.com`) with a certificate fingerprint but no client id?

I've tried the client id on the front end by running `ga.getAll()[0].get('clientId');` in the browser console but that does not work trying different variations with and without `.apps.googleusercontent.com` affixed.

Any ideas?

**Comment by tomhorvat** [comment]
Try clicking on the address!

**Comment by WolfieZero** [comment]
Ah, didn't notice that at all (I blame bad styles on Google's side). But it's one of the combinations I used so there is an issue related to #26 still that could need addressing?

**Comment by tomhorvat** [comment]
Did you add xx-xxx@developer.gserviceaccount.com as a new user with read permissions to your Analytics account?
