### ISSUE TITLE
Can't find "View id" with new GA account

### ISSUE THREAD

**Issue by cdo9** [spatie/laravel-analytics#371]
Hello, i created a new GA account recently, and i can't find the `View section`, I only have the `Account section` and `Property section`. On my other GA account i have no issues. Do you know why? And a workaround ?

**Comment by cdo9** [comment]
I found the issue, when creating a new property, you need to check the "Create a Universal Analytics Property" checkbox.

**Comment by kirkbushell** [comment]
The package needs to move toward supporting GA4, as Universal analytics will eventually be deprecated.

**Comment by freekmurze** [comment]
We'll start working on this soon 👍

**Comment by winnerawan** [comment]
any update?
