### ISSUE TITLE
Update Google Console  instructions

### ISSUE THREAD

**Issue by richardfeliciano** [spatie/laravel-analytics#373]
Google updated api console UI, and now this instructions does not match the new UI.

**Comment by freekmurze** [comment]
Feel free to send a PR that updates our readme

**Comment by Oxicode** [comment]
@richardfeliciano  please 🙏

**Comment by warmwhisky** [comment]
I found this article which helped me get it working with Analytics V4
[https://codelapan.com/post/google-analytics-laravel](https://codelapan.com/post/google-analytics-laravel)
