### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by myles800** [spatie/laravel-analytics#374]
Hi,
I implemented this library in mij laravel project, but i get this error. 
{ "error": { "code": 403, "message": "User does not have sufficient permissions for this profile.", "errors": [ { "message": "User does not have sufficient permissions for this profile.", "domain": "global", "reason": "insufficientPermissions" } ] } }

Analitics does not give a view id anymore so, I tried my property id and my account id, but non work.
Can you help me?

**Comment by fahadali1** [comment]
You can find it by clicking on Show advanced options (when you create a new property):

![Capture](https://user-images.githubusercontent.com/40367179/101612177-2d6ca900-3a2c-11eb-871a-560f186f052d.PNG)
