### ISSUE TITLE
Documentation does not match implementation.

### ISSUE THREAD

**Issue by zero-to-prod** [spatie/laravel-analytics#380]
In the documentation states to use: `Analytics::fetchMostVisitedPages();` However, this is a static method in the package source.

Please advise.

I am using:
![image](https://user-images.githubusercontent.com/61474950/103099000-c8dc4d00-45da-11eb-83f7-fecde659c690.png)

![image](https://user-images.githubusercontent.com/61474950/103098932-92063700-45da-11eb-8e9c-9140c8c9b6ff.png)

**Comment by freekmurze** [comment]
You can use the facade to call all methods statically

```
\Analytics::fetchVisitorsAndPageViews(Period::days(7))
```

**Comment by zero-to-prod** [comment]
Thank you Freek.

What was throwing me was my IDE:
![image](https://user-images.githubusercontent.com/61474950/103155748-8482b580-4770-11eb-9243-59a42339cd52.png)


It does work as documented.
