### ISSUE TITLE
Class 'Analytics' not found

### ISSUE THREAD

**Issue by mprince2k18** [spatie/laravel-analytics#387]
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use Analytics;
use LaravelAnalytics;
use Spatie\Analytics\Period;
class AnalyticsController extends Controller
{
    public function index()
    {
        return \Analytics::fetchMostVisitedPages(Period::days(7));
    }
}

This is the controller code. I am facing Class 'Analytics' not found.

**Comment by Sn0wCrack** [comment]
You should be injecting the Analytics class directly into your controller function or using the Analytics Facade for this.

Similar to the following:

```php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Collection;
use Spatie\Analytics\Period
use Spatie\Analytics\Analytics;
use Spatie\Analytics\AnalyticsFacade;

class AnalyticsController extends Controller
{
    // Injected 
    public function injection(Analytics $analytics)
    {
        return $analytics->fetchMostVisitedPages(Period::days(7));
    }

    // Facade

   public function facade()
   {
       return AnalyticsFacade::fetchMostVisitedPages(Period::days(7));
   }
}
```
