### ISSUE TITLE
performQuery method signature requiring wrong return type

### ISSUE THREAD

**Issue by skeets23** [spatie/laravel-analytics#398]
The performQuery() method returns an instance of Google_Service_Analytics_GaData. This is fine, but the method signature is requiring it to return `array | null`. So if strict types are enabled in PHP (it is by default), this blows up with:

```
Spatie\Analytics\AnalyticsClient::performQuery(): Return value must be of type ?array, Google_Service_Analytics_GaData returned
```

This can be reproduced by making any call to `Analytics::performQuery()` with strict types enabled.

**Comment by WebMedic-X** [comment]
Having the same issue here after upgrading to Laravel 8

**Comment by saifvikishop** [comment]
Having the same issue 😣🤐

**Comment by GuerfiHamza** [comment]
Me too having the same issue

**Comment by NautHnil** [comment]
Me too having the same issue.

![image](https://user-images.githubusercontent.com/2637746/118354920-92a66680-b597-11eb-9d4b-9e0ac667ab60.png)

**Comment by WebMedic-X** [comment]
to everyone facing this problem

the solution is here: https://github.com/spatie/laravel-analytics/pull/402/commits/adf8a0bb6aaee013d622cb6f4fa194a6a9b9e189

enjoy!

**Comment by juanparati** [comment]
I also facing the same issue with Laravel 8

**Comment by elfeffe** [comment]
Me too
