### ISSUE TITLE
Graph ?

### ISSUE THREAD

**Issue by macikgoz25** [spatie/laravel-analytics#42]
Hello, thank you for your package. I installed package. Then I obtain json but I can not show graph. Example output :

[{"date":{"date":"2015-12-26 18:13:05.000000","timezone_type":3,"timezone":"UTC"},"visitors":"0","pageViews":"0"},{"date":{"date":"2015-12-27 18:13:05.000000","timezone_type":3,"timezone":"UTC"},"visitors":"0","pageViews":"0"},{"date":{"date":"2015-12-28 18:13:05.000000","timezone_type":3,"timezone":"UTC"},"visitors":"0","pageViews":"0"},{"date":{"date":"2015-12-29 18:13:05.000000","timezone_type":3,"timezone":"UTC"},"visitors":"0","pageViews":"0"},{"date":{"date":"2015-12-30 18:13:05.000000","timezone_type":3,"timezone":"UTC"},"visitors":"0","pageViews":"0"},{"date":{"date":"2015-12-31 18:13:05.000000","timezone_type":3,"timezone":"UTC"},"visitors":"0","pageViews":"0"},{"date":{"date":"2016-01-01 18:13:05.000000","timezone_type":3,"timezone":"UTC"},"visitors":"0","pageViews":"0"},{"date":{"date":"2016-01-02 18:13:05.000000","timezone_type":3,"timezone":"UTC"},"visitors":"0","pageViews":"0"}]

I use $analyticsData = \LaravelAnalytics::getVisitorsAndPageViews(7);

How Can I show ?

**Comment by trevorgreenleaf** [comment]
@macikgoz25 

You have to pass the data to chart.js.
Sample code for getting the current week vs last week:

**LARAVEL**
I am also using Carbon. But you can just strip that out. The trick here is to just use (lists) on what you want from the array. Then pass that to (data) in chart.js

``` php
$last_weeks_vists = Analytics::getVisitorsAndPageViewsForPeriod(Carbon::now()->subDays(7)->startOfWeek(), Carbon::now()->subDays(7)->endOfWeek(), $groupBy = 'date')->lists('visitors');
$this_weeks_vists = Analytics::getVisitorsAndPageViewsForPeriod(Carbon::now()->startOfWeek(), Carbon::now()->endOfWeek(), $groupBy = 'date')->lists('visitors');
```
   	
**HTML**
``` html 
<h3>This Week vs Last Week</h3>
   <canvas id="this_week_vs_last"></canvas>
   <div id="this_week_vs_last_legend" class="chart-legend"></div>
```




**CHART JS**
   ``` javascript 
var ctx = $("#this_week_vs_last").get(0).getContext("2d"); 
    var data = {
        labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat","Sun"],
        datasets: [
            {
                label: "Last Week",
                fillColor: "rgba(220,220,220,0.2)",
                strokeColor: "rgba(220,220,220,1)",
                pointColor: "rgba(220,220,220,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                data: {!! json_encode($last_weeks_vists) !!}
            },
            {
                label: "This Week",
                fillColor: "rgba(13,172,222, .5)",
                strokeColor: "rgba(13,172,222,1)",
                pointColor: "rgba(13,172,222,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                data: {!! json_encode($this_weeks_vists) !!}
            }
        ]
    };
   var this_week_vs_last = new Chart(ctx).Line(data);
   document.getElementById('this_week_vs_last_legend').innerHTML = this_week_vs_last.generateLegend();
```

Hope that helps.

**Comment by freekmurze** [comment]
Thanks for answering this @trevorgreenleaf :+1:

**Comment by DeeJaVu** [comment]
@trevorgreenleaf omg it works

**Comment by wa05** [comment]
@trevorgreenleaf any solution for this:

BadMethodCallException in Macroable.php line 74:
Method lists does not exist .. 

Thanks

**Comment by shinokada** [comment]
For v2.3.1, this doesn't work.

```
$last_weeks_vists = Analytics::getVisitorsAndPageViewsForPeriod(Carbon::now()->subDays(7)->startOfWeek(), Carbon::now()->subDays(7)->endOfWeek(), $groupBy = 'date')->lists('visitors');
$this_weeks_vists = Analytics::getVisitorsAndPageViewsForPeriod(Carbon::now()->startOfWeek(), Carbon::now()->endOfWeek(), $groupBy = 'date')->lists('visitors');
```

It seems I need to use this but I get an error.

> ErrorException in Collection.php line 462:
> array_key_exists(): The first argument should be either a string or an integer

```
$startDate = Carbon::now()->subDays(7)->startOfWeek();
$endDate = Carbon::now();
$this->data['last_weeks_vists'] = Analytics::fetchVisitorsAndPageViews(Period::create($startDate,$endDate))->groupBy('date')->lists('visitors');

$startDate = Carbon::now()->startOfWeek();
$endDate = Carbon::now()->endOfWeek();
$this->data['this_weeks_vists'] = Analytics::fetchVisitorsAndPageViews(Period::create($startDate,$endDate))->groupBy('date')->lists('visitors');

```

**Comment by Miljoen** [comment]
@shinokada I'm running into the same issue, have you found a solution for this one yet?
