### ISSUE TITLE
Error refreshing the OAuth2 token

### ISSUE THREAD

**Issue by fantashi** [spatie/laravel-analytics#45]
Google_Auth_Exception in OAuth2.php line 364:
Error refreshing the OAuth2 token, message: '{
"error" : "invalid_grant"
}'

**Comment by freekmurze** [comment]
Check the instructions provided in this readme or the documentation that Google provides.

**Comment by siddharthghedia** [comment]
@fantashi were you able to solve the issue? If so how, can you guide me? 

I am having the same issue.

**Comment by DeeJaVu** [comment]
@siddharthghedia  same issue, did you fix it ?

**Comment by damnhalfling** [comment]
i have the same problem.

I create a new service but not help. Somebody have an idea??
