### ISSUE TITLE
[possible enhancement]Mark as Deferred ServiceProvider

### ISSUE THREAD

**Issue by davkap92** [spatie/laravel-analytics#46]
Hi,
Thank you for this library,
Maybe I don't fully understand, but could this perhaps be marked as a Deferred provider
(https://laravel.com/docs/master/providers#deferred-providers), so only loaded when needed, As I only need it for certain commands and am hesitant to keep adding service providers and unnecessarily bloating my laravel instance. 
Thanks

**Comment by freekmurze** [comment]
I don't think that a non deferred provider will have a great impact on performance. I'll research it at bit and will update the service provider if it turns out this has beneficial effects.
