### ISSUE TITLE
Is it possible to add new sites, or run custom api commands not official supported

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-analytics#47]
Love your project so far! I was wondering if it's possible to use your library to programatically create new sites. I am building a sort of site-generator using Laravel and would like to do everything from the code. If this is not built-in then is it possible to use your library to make calls to official google analytics api endpoints that are not built into your project?

Thanks

**Comment by freekmurze** [comment]
The scope of this package is retrieving data from existing properties. If there's not too much code involved it'd accept a PR that adds creating a GA-properties and other endpoints.
