### ISSUE TITLE
possible to programatically change the configuration options for current session?

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-analytics#48]
Since I am building a site-generator I would like to be able to retrieve the siteId, clientId, serviceEmail and certificatePath from a database and query using those parameters for the current session.

I see you have a setter for the siteId but was wondering if it would be very hard to make it possible to instead change the configuration settings and have those be used for the current session?

**Comment by freekmurze** [comment]
If you want to change those parameters at runtime, it might be easier to create a AnalyticsFactory in your application that builds up a `LaravelAnalytics`-object. 

In the service provider you can learn how such an object should be build up.
