### ISSUE TITLE
Is there any way we can attach siteId / clientId dynamically ? 

### ISSUE THREAD

**Issue by hemratna** [spatie/laravel-analytics#51]
Hi,
Is there any way we can attach all configuration  dynamically ? 
This will be helpful to create dashboard where we can show data from multiple account / site ?
Thank you for awesome package.

**Comment by freekmurze** [comment]
Out of the box the package doesn't do this, but you could try to build up your own `Spatie\LaravelAnalytics\LaravelAnalytics`-object.

Take a look at [the code in the serviceprovider](https://github.com/spatie/laravel-analytics/blob/master/src/LaravelAnalyticsServiceProvider.php#L28-L32) to learn how this is done.
