### ISSUE TITLE
Error  after installation

### ISSUE THREAD

**Issue by dnsimmons** [spatie/laravel-analytics#52]
After calling:

/*
* $analyticsData now contains a Collection with 3 columns: "date", "visitors" and "pageViews"
*/
$analyticsData = \LaravelAnalytics::getVisitorsAndPageViews(7);

Produces the following error:

Google_Exception in Resource.php line 169:
(get) missing required param: 'ids'

I do see the ids as null. Any ideas ?

**Comment by freekmurze** [comment]
Did you specify a site id in the config file? Please review the installation instructions of this package.

**Comment by hoangtri239** [comment]
I did config siteId and it's still not working now

**Comment by freekmurze** [comment]
Do you see that value when running `config('analytics')`?

**Comment by hoangtri239** [comment]
Where to run that config sir ?

**Comment by freekmurze** [comment]
You could run it in a tinker session.

**Comment by fatenfalfoul** [comment]
Good morning Sir, 
Please I run the command line but siteId is null even I get it from the prperty (view Id) 
Help please
