### ISSUE TITLE
Error with method "calculateNumberOfDays"

### ISSUE THREAD

**Issue by vladvisinescu** [spatie/laravel-analytics#53]
So I`ve configured everything, methods are being called, but this particular "protected" method is not. 

I can access the method directly and it works fine, but other methods can not. How could I debug something like this? 

Thanks * 100

**Comment by freekmurze** [comment]
That method is protected meaning you cannot call it from outside of the object.

**Comment by vladvisinescu** [comment]
later edit: I can`t seem to be able to access any methods listed in this package, actually. 
I know the method is protected, I just wanted to check my sanity, made it public and it worked:)
So, is there any way I can debug this?
I`m running PHP 5.6.15, if it counts...

**Comment by freekmurze** [comment]
What are you trying to do exactly? To my knowledge the method is working fine. Are you getting wrong results?

You can debug the method by putting some `echo` statements inside of it.

**Comment by vladvisinescu** [comment]
So:
I\`m calling "getVisitorsAndPageViewsForPeriod", for example, and that returns BadMethodCallException in Controller.php line 107: Method [performQuery] does not exist.

I\`m calling "getMostVisitedPages" and that returns 
BadMethodCallException in Controller.php line 107: Method [calculateNumberOfDays] does not exist.

Anything I call in my controller returns and error like that.

**Comment by vladvisinescu** [comment]
tried dumpautoload, cache:clear, config:clear, no results

**Comment by freekmurze** [comment]
Did you import the `LaravelAnalytics` facade (not the actual class) in your controller?
