### ISSUE TITLE
Google_Auth_Exception in OAuth2.php

### ISSUE THREAD

**Issue by tiroldesign** [spatie/laravel-analytics#55]
hi,

can't get it up and running. I followed the instructions many times - but the credentials doesn't match as mentioned in the config file. If I create ony a service account there is no:
xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com

I only can find something like:
projekt@projekt.iam.gserviceaccount.com

the xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com is only generated if I use OAuth-Client ...

so I always get the error:
`Google_Auth_Exception in OAuth2.php line 364:
Error refreshing the OAuth2 token, message: '{
"error" : "invalid_grant",
"error_description" : "Invalid issuer: null"
}'`

very frustrating ... - maybe someone could help!

**Comment by tiroldesign** [comment]
remove the env from the config - you should describe this in your readme - searching many hours for that!!
https://github.com/spatie/laravel-analytics/issues/27

**Comment by mucskaati** [comment]
Hi, i always get the error: 

Error calling GET https://www.googleapis.com/analytics/v3/data/ga?ids=116149027&start-date=2016-04-13&end-date=2016-04-20&metrics=ga%3Avisits%2Cga%3Apageviews&dimensions=ga%3Adate: (400) Invalid value '116149027'. Values must match the following regular expression: 'ga:[0-9]+'

Where I find GA:.......code, what can i find is only UA code.

Thanks

**Comment by freekmurze** [comment]
There are some instruction on how to find this value in the readme:
---
To find the right value for siteId log in to Google Analytics go the the Admin section. In the property-column select the website name of which you want to retrieve data, then click View Settings in the View-column. The value presented as View Id prepended with 'ga:' can be used as siteId.
---
