### ISSUE TITLE
Concurrent requests

### ISSUE THREAD

**Issue by Geoffzable** [spatie/laravel-analytics#56]
Hi,

I am hitting Quota errors that I am exceeding the User Rate Limit.
According to https://developers.google.com/analytics/devguides/config/mgmt/v3/limits-quotas#overview,
I am exceeding 10 request / s and I would like to scale down the amount of requests to the Analytics API. One way would be using the SetDefer() to stack up Requests and execute them at once.

How do I do this with this package without rewriting most of the logic.

Thanks in advance.

**Comment by freekmurze** [comment]
Your application is responsible for not hitting any rate limits.
