### ISSUE TITLE
Lumen error

### ISSUE THREAD

**Issue by mizansyed** [spatie/laravel-analytics#58]
Hi 

Does this package work with Lumen as is? 

I get ` FatalErrorException in LaravelAnalyticsServiceProvider.php line 65:
Class 'File' not found
in LaravelAnalyticsServiceProvider.php line 65
at Application->handleShutdown() in RegistersExceptionHandlers.php line 55
at Application->Laravel\Lumen\Concerns\{closure}() `

when I try a method.

**Comment by mizansyed** [comment]
Looks like you have to register this class, using `class_alias`.

**Comment by sebastiandedeyne** [comment]
Actually using facades in a Laravel practice generally isn't a good idea, so our bad for that 🙊 

Going to tag a facadeless release soon, then it should work out of the box.

**Comment by freekmurze** [comment]
Facadeless release has been tagged: `v1.4.0`
