### ISSUE TITLE
Get Top Keywords now Stop Working, always return null

### ISSUE THREAD

**Issue by David-Kurniawan** [spatie/laravel-analytics#63]
`$topkeyga = LaravelAnalytics::getTopKeywords(5,10);`

and result is :
```
    Illuminate\Support\Collection Object
    (
        [items:protected] => Array
            (
            )
    )
```

**Comment by freekmurze** [comment]
This seems to work just fine. Are you using this on a new ga-property? It takes a little bit of time for Google to populate this answer.

**Comment by freekmurze** [comment]
Reopen this if you're still having problems.
