### ISSUE TITLE
Google API system changed

### ISSUE THREAD

**Issue by robwilde** [spatie/laravel-analytics#65]
I am trying to work through the guide to setup the keys needed for the config but it seems google has changed their authentication system somewhat.

Your guide advises to get "values for the serviceEmail and clientId" but when I create a service account with a p12 key, I get Service account ID and Key ID.

Would this replace serviceEmail and clientId, respectively ?

**Comment by xeroky** [comment]
I just encountered the same problem

**Comment by Meersie** [comment]
Yup ... same here...

**Comment by xeroky** [comment]
ANALYTICS_SITE_ID='ga:xxxxxxxxx'
Google Analytics -> Admin -> View -> View Settings -> View ID -> xxxxxxxx

ANALYTICS_CLIENT_ID='xxxxxxxxx.apps.googleusercontent.com'
console.developers.google.com -> left menú, APIs Admin -> Credentials -> ID = xxxxxxxxx

ANALYTICS_SERVICE_EMAIL='x'
console.developers.google.com -> left menú, IAM and Admin -> Service account -> Id Service Account = x

Works for me!

**Comment by Meersie** [comment]
Indeed ... that did the trick.

Also don't forget this as next step:

**Make sure you've added the ANALYTICS_SERVICE_EMAIL to the Google Analytics Account otherwise you will get a 403: User does not have any Google Analytics Account error.**

**Comment by freekmurze** [comment]
Closing this as @xeroky provided the right answer.

Thank you very much @xeroky
