### ISSUE TITLE
Google Account Feed

### ISSUE THREAD

**Issue by markhilton** [spatie/laravel-analytics#66]
Is there a way I can use this API to call Google Analytics Account Feed in order to get a list of segments with their IDs?

**Comment by freekmurze** [comment]
I'm not familiar with Google Analytics Account Feed. 

The package does provided a method do perform any query you want on the Analytics API: https://github.com/spatie/laravel-analytics#all-other-google-analytics-queries

**Comment by markhilton** [comment]
Im looking to be able to execute API call that I think has a different endpoint thatn perform query: https://www.googleapis.com/analytics/v3/management/segments

https://developers.google.com/analytics/devguides/config/mgmt/v3/mgmtReference/management/segments/list#examples

**Comment by robwilde** [comment]
exactly what I am trying to do. Seems like the Spatie is hard coded to the analytics service and not management.
I am working on using the Google API, that Spatie references, and use the 
Google_Service_Analytics Class in
vendor/google/apiclient/src/Google/Service/Analytics.php

I still rather new to Laravel so if anyone does work it out, would really appreciate some reference to how it was done. Laracasts is good but a lot of the Service Provider training is from Laravel 4, still getting my head around it. 

Hope that helps
