### ISSUE TITLE
getTopKeyWordsForPeriod is missing

### ISSUE THREAD

**Issue by sangnguyenplus** [spatie/laravel-analytics#70]
Hi @freekmurze,
getTopKeyWordsForPeriod is missing and it makes my app broken. Can you add this function to src/Analytics.php.
The new function with new name fetchTopKeyWords.
Thanks!

**Comment by freekmurze** [comment]
I left out the function that fetches the top keywords because in many cases Google doesn't record the key word anymore: https://googleblog.blogspot.be/2011/10/making-search-more-secure.html

However, I'd accept a PR that adds it back to the package.
