### ISSUE TITLE
getActiveUsers is missin

### ISSUE THREAD

**Issue by kadircanerergun** [spatie/laravel-analytics#71]
New version hasn't getActiveUsers method? Can you add it?

**Comment by freekmurze** [comment]
Adding function for real time data would add too much complexity (different endpoint, different cache settings, etc...) Feel free the extends the `Spatie\Analytics\Analytics` class in your project to add the method yourself.

**Comment by SimonJ** [comment]
oh man :/ i need this too

**Comment by foufos** [comment]
Not sure if anyone is still looking for this but you can get the data through the Google_Service_Analytics object
`Analytics::getAnalyticsService()->data_realtime->get(env('ANALYTICS_VIEW_ID'), 'rt:activeVisitors')->totalsForAllResults['rt:activeVisitors']`

**Comment by edwardkarlsson** [comment]
Yupp, @foufos That seems to work, except I have to add `ga:` in front of the analytics view id. So the string that works for me is:
`...getAnalyticsService()->data_realtime->get('ga:'.env('ANALYTICS_VIEW_ID'), 'rt:activeVisitors')->totalsForAllResults['rt:activeVisitors']`

**Comment by raffobaffo** [comment]
> Yupp, @foufos That seems to work, except I have to add `ga:` in front of the analytics view id. So the string that works for me is:
> `...getAnalyticsService()->data_realtime->get('ga:'.env('ANALYTICS_VIEW_ID'), 'rt:activeVisitors')->totalsForAllResults['rt:activeVisitors']`

Probably you just have to add "ga:" in front of your ANALYTICS_VIEW_ID in your  .env file
