### ISSUE TITLE
credentialsJsonDoesNotExist didn't send argument

### ISSUE THREAD

**Issue by kent62001** [spatie/laravel-analytics#72]
Hello,

When I misplace the google service account credentials json, it comes out this error

> FatalThrowableError in InvalidConfiguration.php line 14:
> Type error: Argument 1 passed to Spatie\Analytics\Exceptions\InvalidConfiguration::credentialsJsonDoesNotExist() must be of the type string, none given, called in /vendor/spatie/laravel-analytics/src/AnalyticsServiceProvider.php on line 57

And In AnalyticsServiceProvider line 57 is

> throw InvalidConfiguration::credentialsJsonDoesNotExist();

Change to 

> throw InvalidConfiguration::credentialsJsonDoesNotExist($analyticsConfig['service_account_credentials_json']);

and the right exception showing up :)

This is just a small problem, I still really like this tool 👍

**Comment by freekmurze** [comment]
Thanks for bringing this to my attention. It has been fixed in `2.1.0`.
