### ISSUE TITLE
Feature Request for `fetchMostVisitedPages`

### ISSUE THREAD

**Issue by ericbarnes** [spatie/laravel-analytics#73]
It would be nice if `fetchMostVisitedPages` also included the `ga:pageTitle` in the dimensions that way if you are making a list of "top pages" you can display the titles.

**Comment by freekmurze** [comment]
Hi Eric,

I've added your feature request to the package.

In the newly tagged version `2.1.0` functions `fetchVisitorsAndPageViews` and `fetchMostVisitedPages` will return `pageTitle`.

**Comment by rypsx** [comment]
It's a good idea, but in reality it's problematic ... Indeed, if you change the name of the page, we find several times the same page but counted several times. So, I tried to recreate an array behind Analytics :: fetchMostVisitedPages(), but the execution time becomes too large. I deplore this feature which is more embarrassing than anything else.

**Comment by ericbarnes** [comment]
If I remember correctly, GA didn't have any thing better to use outside of page title so of course it'll be brittle. If you can find another dimension I think it'd be nicer.

**Comment by rypsx** [comment]
`If you can find another dimension I think it'd be nicer`
What are you thinking about ?
