### ISSUE TITLE
Valid view id?

### ISSUE THREAD

**Issue by Meersie** [spatie/laravel-analytics#76]
Hey - trying to upgrade from version 1 to 2 in my Laravel project.
I followed every step (really ... every step) in the README to get all the needed config settings.
Even wiped out my Google Developers project to start fresh.

But I keep ending up with 

**ErrorException in InvalidConfiguration.php line 11:
You must provide a valid view id.**

I have checked the view id multiple times and it is the correct one.
Any idea what could be the problem? Really in the dark here...

**Comment by freekmurze** [comment]
What is the output of `config('laravel-analytics');`

**Comment by Meersie** [comment]
Weird ... the view id was empty when using config('laravel-analytics');.
After removing the env() around the viewid everything worked fine...
