### ISSUE TITLE
how to retrieve real time active users?

### ISSUE THREAD

**Issue by michelecurletta** [spatie/laravel-analytics#77]
Hi,
the old version of package was providing a method like this: `LaravelAnalytics::getActiveUsers()`.
With the new major version (2.x), how can retrieve the real time active users?
Could you help me to the find the right query to perform?
Why don't still provide the feature through a dedicated method like the older version of the package? It is very useful and up&running feature.
Maybe [this docs](https://developers.google.com/analytics/devguides/reporting/realtime/v3/reference/data/realtime/get) will be useful

Thank you so much

**Comment by freekmurze** [comment]
See #71
