### ISSUE TITLE
   [Symfony\Component\Debug\Exception\FatalErrorException]   Class 'Spatie\Analytics\AnalyticsServiceProvider' not found

### ISSUE THREAD

**Issue by JoseCage** [spatie/laravel-analytics#79]
I installed the package by composer and following the steps described in the documentation, but I can not copy the package configuration file for error account below:

<code>
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Spatie\Analytics\AnalyticsServiceProvider' not found
</code>

I would appreciate some help in ways to be able to solve this problem please. I've tried uninstalling the package and re-install but the error persists.

**Comment by michelecurletta** [comment]
I've solved the issue changing the script section of composer.json like this:

`"scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan cache:clear",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan cache:clear",
            "php artisan optimize"
        ]
    },`

**Comment by JoseCage** [comment]
@michelecurletta i have followed your example but it not works for me.. The error keep the same..

$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan cache:clear
Application cache cleared!
> php artisan optimize
Generating optimized class loader

<code>
$ php artisan vendor:publish --provider="Spatie\Analytics\AnalyticsServiceProvider"


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Spatie\Analytics\AnalyticsServiceProvider' not found
</code>

**Comment by sebastiandedeyne** [comment]
Did you add the provider to the `providers` array in `config/app.php`?

**Comment by JoseCage** [comment]
Yes @sebastiandedeyne i have added The ServiceProvider and also the Alias and after i run the vendor:publish (with the right arguments) and return the error above...

**Comment by michelecurletta** [comment]
Have you tried deleting manually all folders related to cache?

**Comment by freekmurze** [comment]
Could you try installing the package into a fresh installation of Laravel?

**Comment by luisheumann** [comment]
the error is because you have installed php 5.5, and run "composer require Spatie / laravel-analytics" automatically compatible version is installed with this version which is the "Spatie / laravel-analytics": "1.4" ... to fix you to update the php to version 7 and also to run the composer. the version "" Spatie / laravel-analytics "was installed:" ^ 2.1 "..

**Comment by SadiqUltra** [comment]
Try this 
// config/app.php
'providers' => [
    ...
    Spatie\LaravelAnalytics\LaravelAnalyticsServiceProvider::class,
    ...
];

// config/app.php
'aliases' => [
    ...
    'Analytics' => Spatie\LaravelAnalytics\LaravelAnalyticsFacade::class,
    ...
];


php artisan vendor:publish --provider="Spatie\LaravelAnalytics\LaravelAnalyticsServiceProvider"

**Comment by JoseCage** [comment]
@michelecurletta The folder "storage/framework/cache" is empty..

**Comment by gppack** [comment]
try to install newly &
add this line to provider array in app.php
Spatie\LaravelAnalytics\LaravelAnalyticsServiceProvider::class
and 
'Analytics' => Spatie\LaravelAnalytics\LaravelAnalyticsFacade::class,
in aliases array.

then try to publish using the below command
php artisan vendor:publish --provider="Spatie\LaravelAnalytics\LaravelAnalyticsServiceProvider"

**Comment by JoseCage** [comment]
Thanks for all for your support.. I have done like @gppack say's and its work.. 

Thanks for attention.. :+1:  :beers:

**Comment by duikb00t** [comment]
What namespace are you using? I get an error on 'Not found Period'.

Is it possible this line of code not yet correct?
`use Spatie\Analytics\Period;`

**Comment by freekmurze** [comment]
@duikb00t could you verify that you have PHP 7 on your machine and composer picks the v2 of the package to install?

**Comment by JoseCage** [comment]
@duikb00t i get same error when i define `use Spatie\Analytics\Period;` in my controler.

@freekmurze For this project i'musing windows10 and i have installed wampserver. But my php version isn't 7..

**Comment by freekmurze** [comment]
@JoseCage If you are not using PHP 7 composer will use v1 of the package. Please refer to the document of that version: https://github.com/spatie/laravel-analytics/tree/1.4.1

I highly recommend and upgrade to PHP 7 :-)

**Comment by Borgoroth** [comment]
@gppack  worked for me, thanks a lot dude!

**Comment by freekmurze** [comment]
Reopen if this is still a problem for anyone.

**Comment by JoseCage** [comment]
Maybe it did not work for me because of my development environment. I will take the tests on my machine with ubuntu and has php7 and see what the outcome. Thank you all.

**Comment by barjas** [comment]
The issue is still there! i have php 5
i get the following error 
```
PHP Fatal error:  Class 'Spatie\Analytics\AnalyticsServiceProvider' not found in
c:\xampp\htdocs\laravel\vendor\laravel\framework\src\Illuminate\Founda
tion\ProviderRepository.php on line 146
```

**Comment by masterbits** [comment]
here is the fix to all of this issue...
https://github.com/spatie/laravel-analytics/issues/80

**Comment by masterbits** [comment]
here is the fix to all of this issues...
https://github.com/spatie/laravel-analytics/issues/80

**Comment by romulo-rocha** [comment]
I think the author should document this alternative for PHP < 7, so we won't have to google for a solution anymore.

**Comment by metinbulak** [comment]
it is different provider between
        Spatie\Analytics\AnalyticsServiceProvider::class,  (this has eror)    and
        Spatie\LaravelAnalytics\LaravelAnalyticsServiceProvider::class,  (this not)

**Comment by kamranbhutto** [comment]
Argument 1 passed to Illuminate\Auth\EloquentUserProvider::validateCredentials() must be an instance of Illuminate\Contracts\Auth\Authenticatable, instance of App\Models\Admin\Admin given, called in C:\wamp\www\musicapp\vendor\laravel\framework\src\Illuminate\Auth\SessionGuard.php on line 377

**Comment by rupesh-tech** [comment]
"message": "Argument 3 passed to Lcobucci\\JWT\\Signer\\Hmac::doVerify() must be an instance of Lcobucci\\JWT\\Signer\\Key, null given, called in C:\\easy-test-web\\vendor\\lcobucci\\jwt\\src\\Signer\\BaseSigner.php on line 44",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "C:\\easy-test-web\\vendor\\lcobucci\\jwt\\src\\Signer\\Hmac.php",
    "line": 29,
when i use jwt middleware how can i solve
