### ISSUE TITLE
Fix config/app.php in the tutorial

### ISSUE THREAD

**Issue by gusilveiramp** [spatie/laravel-analytics#80]
Congratulations for the work. It is excellent, but the path to the classes in the **config/app.php** file are wrong. I suggest you correct it on the install tutorial.

**Wrong:** 
'providers' => [
    ...
    Spatie\Analytics\AnalyticsServiceProvider::class,
    ...
];

**Right:**
'providers' => [
    ...
    Spatie\LaravelAnalytics\LaravelAnalyticsServiceProvider::class,
    ...
];

**Wrong:**
'aliases' => [
    ...
    'Analytics' => Spatie\Analytics\AnalyticsFacade::class,
    ...
];

**Right:**
// config/app.php
'aliases' => [
    ...
    'Analytics' => Spatie\LaravelAnalytics\LaravelAnalyticsFacade::class,
    ...
];

**Comment by gusilveiramp** [comment]
Please, fix the "How to obtain the credentials to communicate with Google Analytics" topic too.
When we generate the config file with the command: _**php artisan vendor:publish --provider="Spatie\Analytics\AnalyticsServiceProvider"**_, the generated file is different from the tutorial file. I believe the tutorial is outdated.

In the current file you work with **.P12 key,** **Site ID**, **Client ID** and **Service Email**. Instruct about getting those keys would be great to users with less experience.

**Comment by freekmurze** [comment]
The docs seems fine to me. 

I'm thinking that composer installed v1 of this package on your machine, probably because you're not running PHP 7. If so, the docs for v1 can be found here: https://github.com/spatie/laravel-analytics/tree/1.4.1
