### ISSUE TITLE
can u include this perform query sir?

### ISSUE THREAD

**Issue by tonz341** [spatie/laravel-analytics#81]
Please include real time method sir query. Im having an hard time to overide your works :(

**Comment by tonz341** [comment]
i add following methods to analytics.php

public function performRealTimeQuery(string $metrics, array $others = [])
    {
        return $this->client->performRealTimeQuery(
            $this->viewId,
            $metrics,
            $others
        );
    }

**Comment by tonz341** [comment]
and another method to AnalyticsClient..

 public function performRealTimeQuery(string $viewId, string $metrics, array $others = [])
    {
        $cacheName = $this->determineCacheName(func_get_args());

        if ($this->cacheLifeTimeInMinutes == 0) {
            $this->cache->forget($cacheName);
        }

        return $this->cache->remember($cacheName, $this->cacheLifeTimeInMinutes, function () use ($viewId, $metrics, $others) {

            return $this->service->data_realtime->get(
                "ga:{$viewId}",
                $metrics,
                $others
            );
        });
    }

**Comment by tonz341** [comment]
its working but if i composer update all modified will be reset :(

**Comment by michelecurletta** [comment]
@tonz341 you should not add the new method to the original class, but extend @freekmurze's class and add it to the extended onew

**Comment by freekmurze** [comment]
@michelecurletta responded with the correct answer.

**Comment by tonz341** [comment]
hi freek.. how can i override ur public function constructor with a new analytics client in the new analytics class ? when i try to change the AnalyticsClient extended with its original class it giving me an error of Type error: Argument 1 passed to __construct() must be an instance of bla bla bla

**Comment by tonz341** [comment]
do u have any steps how to properly extend ur class sir? Ive already override the provider, analytics and analyticsclient..

**Comment by tonz341** [comment]
when overriding analytics client. still analaytics use the old analytics client.. dont know what to do :(
