### ISSUE TITLE
Config File parameters Issue

### ISSUE THREAD

**Issue by cw-rahulwankhade** [spatie/laravel-analytics#82]
In documentation, it is mentioned only 3 properties in Laravel Analyticvs config file i.e.  'view_id', 'service_account_credentials_json', 'cache_lifetime_in_minutes'. 

But after installation and publishing vendor config file contains 6 parameters 
siteId, clientId, serviceEmail, certificatePath, cacheLifetime, realTimeCacheLifetimeInSeconds. From where I will get values of these parameters?

Also when I tried to call Analytics::fetchMostVisitedPages(Period::days(7)), I can not call it statically and when I create the object of LaravelAnalytics class it gives error Argument 1 passed to Spatie\LaravelAnalytics\LaravelAnalytics::__construct() must be an instance of Spatie\LaravelAnalytics\GoogleApiHelper.

Request you to provide the details to sort out these issues?

**Comment by freekmurze** [comment]
You've probably installed a v1 version due to the fact that you're not running PHP 7. Upgrade to PHP 7, run composer update to get v2 of the package.
