### ISSUE TITLE
Why composer update does not add all the classes

### ISSUE THREAD

**Issue by Borgoroth** [spatie/laravel-analytics#84]
When I run composer update it doesn't install Period Classes and Exceptions folder

**Comment by sebastiandedeyne** [comment]
Did composer by chance install the older version instead of the new `v2`?

**Comment by Borgoroth** [comment]
it only installed this:
https://gyazo.com/6d6d8d76ac44ebf157a67233b37641e7

**Comment by sebastiandedeyne** [comment]
That's the source code of version 1 of this package. You'll need to edit your `composer.json` to install v2:

```
"spatie/laravel-analytics": "^2.0.0"
```

Note that v2 requires php7 to install.
