### ISSUE TITLE
Class 'Period' not found

### ISSUE THREAD

**Issue by KrGyan** [spatie/laravel-analytics#88]
I have installed Laravel analytics and when trying to use  $analyticsData = Analytics::fetchVisitorsAndPageViews(Period::days(7));, it is throwing error Class 'Period' not found

**Comment by KrGyan** [comment]
add this line to provider array in app.php
Spatie\LaravelAnalytics\LaravelAnalyticsServiceProvider::class
and 
'Analytics' => Spatie\LaravelAnalytics\LaravelAnalyticsFacade::class,
in aliases array.


These are changes which I made to remove [Symfony\Component\Debug\Exception\FatalErrorException] Class 'Spatie\Analytics\AnalyticsServiceProvider' not found  error earlier

**Comment by freekmurze** [comment]
You probably have PHP5 installed. If that's the case composer will pull in v1 of this package. Upgrade to PHP 7 to get v2.

**Comment by KrGyan** [comment]
I now installed PHP 7.0.8, and used $analyticsData = Analytics::fetchVisitorsAndPageViews(Period::days(7));
    print_r($analyticsData); in my route.php , it is still throwing Class 'Period' not found error.

**Comment by sebastiandedeyne** [comment]
See #90
