### ISSUE TITLE
Integration with Embed API

### ISSUE THREAD

**Issue by zlatevbg** [spatie/laravel-analytics#89]
How could one obtain the ACCESS_TOKEN_FROM_SERVICE_ACCOUNT as shown in [https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/](https://ga-dev-tools.appspot.com/embed-api/server-side-authorization/)

**Comment by freekmurze** [comment]
Hi,

In the latest version of this package (v2) you'll need to download a json file with credentials. I've included full instructions in the readme. I'm not supporting v1 anymore.

**Comment by zlatevbg** [comment]
Hi,

I'm using v2 of the package. 

However because this package doesn't include any front-end / javascript code for displaying the data (e.g. as a chart) I wanted to use the Google Analytics Embed API. 

So, how can I get the ACCESS_TOKEN_FROM_SERVICE_ACCOUNT using your package?

**Comment by freekmurze** [comment]
Client side functionality is out of scope of this package. Please refer to Google's docs on how to use the Embed API.

**Comment by zlatevbg** [comment]
Hi,

I get that. However if I'm not able to get the access token from the json using your package there is no point to using it at all. I better just use the Google Analytics API directly.

Thanks.

**Comment by razvaniacob** [comment]
So I was thinking the same thing. To get the ACCESS_TOKEN_FROM_SERVICE_ACCOUNT to use in Google Analytics Embed API. I used Analytics::getAnalyticsService()->getClient()->getAccessToken() but it returns null. Any thoughts?
