### ISSUE TITLE
Class 'Period' not found

### ISSUE THREAD

**Issue by KrGyan** [spatie/laravel-analytics#90]
I now installed PHP 7.0.8, and used $analyticsData = Analytics::fetchVisitorsAndPageViews(Period::days(7));
print_r($analyticsData); in my route.php , it is still throwing Class 'Period' not found error.

**Comment by sebastiandedeyne** [comment]
Did you import it with a `use` statement?

```php
use Spatie\Analytics\Period;

Analytics::fetchVisitorsAndPageViews(Period::days(7));
```
Note: If you're in something namespaces like a controller, you'll also have to add `use Analytics;`..
