### ISSUE TITLE
Cache Permission issue

### ISSUE THREAD

**Issue by KrGyan** [spatie/laravel-analytics#91]
Hi, 
I am getting below error . I have given 0777 permission to storage folder.

Thanks for your great forum once again in advance !!

at HandleExceptions->handleError('2', 'mkdir(): Permission denied', '/Applications/XAMPP/xamppfiles/htdocs/aestheticplay/vendor/google/apiclient/src/Google/Cache/File.php', '149', array('file' => '98496901ee429988647aa88742efec94', 'forWrite' => true, 'storageDir' => '/var/folders/jq/brjvltt92wv9395rz9m_v7ww0000gn/T/Google_Client/ee'))

Thanks
Gyan

**Comment by KrGyan** [comment]
@sebastiandedeyne , would be looking for your response here, please

**Comment by KrGyan** [comment]
It was problem with mac OS temp folder issue , but now its showing Error calling GET https://www.googleapis.com/analytics/v3/data/ga?ids=ga%3A108219822&start-date=2016-06-30&end-date=2016-07-07&metrics=ga%3Ausers%2Cga%3Apageviews&dimensions=ga%3Adate%2Cga%3ApageTitle: (403) User does not have any Google Analytics account.,


While the view ID is correct, I rechecked that.

**Comment by KrGyan** [comment]
Thanks , its fixed .I fixed it by adding the email address for my service account to the Google Analytics profile I wanted it to access

**Comment by sebastiandedeyne** [comment]
Glad to see it all turned out well 👍
