### ISSUE TITLE
Non static method

### ISSUE THREAD

**Issue by borislemke** [spatie/laravel-analytics#92]
Hi there,
I was just integrating your library into one of my project's and ran into a `Non-static method should not be called statically` issue.

below is the function I use to query my analytics account.
```php
public function query()
    {
        // Just checkin out what this returns
        // return response()->json(Period::days(14));
        return Analytics::fetchVisitorsAndPageViews(Period::days(7));
    }
```

Help would be appreciated!

**Comment by freekmurze** [comment]
You should import the namespace on top of your class

```php
use Analytics;
```

**Comment by borislemke** [comment]
@freekmurze ahh of course, facades. I tried to import the real class instead. Thanks for the help! Love what you guys are doing!
