### ISSUE TITLE
GA Dimension

### ISSUE THREAD

**Issue by KrGyan** [spatie/laravel-analytics#93]
Hi,

I am getting below error while trying to get ga:userGender.

Error calling GET https://www.googleapis.com/analytics/v3/data/ga?ids=ga%3A108219822&start-date=2016-07-09&end-date=2016-07-16&metrics=ga%3A.userGender: (400) Invalid dimension or metric: ga:.userGender

Below is my script

$topGender = Analytics::performQuery(Period::days(7),'ga:.userGender');
print_r($topGender);

**Comment by freekmurze** [comment]
Please refer to [Google's documentation](https://developers.google.com/analytics/devguides/reporting/core/v3/common-queries) to learn what's possible.
