### ISSUE TITLE
New Google Console Developer

### ISSUE THREAD

**Issue by sufianetaouil** [spatie/laravel-analytics#97]
Hi,
Has anyone succeeded to retrieve client Id / service Email from the new google console ?
I'm facing this exception and i'm pretty sure it's because of the bad configuration : 
`Google_Auth_Exception in OAuth2.php line 364:
Error refreshing the OAuth2 token, message: '{
"error" : "invalid_grant",
"error_description" : "Invalid JWT Signature."
}'`

1- In the view setting we're not getting ga:xxxxxxxx we're getting xxxxxxxx so i manually added the ga: at the beginning of the id.
2- We're not getting client id when creating a Service account key, we're getting it when creating an oAuth2 client id, and i believe we don't need this here since it's not mentioned in the documentation.
3- The email address i get from the service account doesn't match the one mentioned in the documentation : xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@developer.gserviceaccount.com
what i'm getting is : prop-41@propertypl-1383.iam.gserviceaccount.com

I guess this is due to the big change of the developer console ?

**Comment by freekmurze** [comment]
I've included some instruction on how to get the right credentials on the developer console.
https://github.com/spatie/laravel-analytics#how-to-obtain-the-credentials-to-communicate-with-google-analytics

Just make sure you're using the latest version of the package (requires PHP 7)

**Comment by sufianetaouil** [comment]
@freekmurze that's the problem i can't, i'm using the 1.4.1 since my client doesn't want to upgrade to php 7

**Comment by xron89** [comment]
Same issues as above, I believe this is no longer supported on any php versions lower than 7 as google don't produce the same keys as they did.

**Comment by freekmurze** [comment]
Then I guess you'll have to update to PHP 7 😄 

I don't give support on the older versions anymore.

**Comment by niknackster** [comment]
@sufianetaouil : did u resolve issue with old php version?
@freekmurze : could you please suggest any work around with this, as i am using shared hosting to host my website and my share hosting provider is having old php version and they are not keen to update it to php7? I am forced to use old one.
